### ISSUE TITLE
Can't run tests

### ISSUE THREAD

**Issue by stasek513** [webdriverio/appium-boilerplate#102]
Hello when I try run tests.   I get error
appium-boilerplate (main) $ npm run ios.app

> appium-boilerplate@5.3.1 ios.app /Users/useName/Projects/appium-boilerplate
> wdio ./config/wdio.ios.app.conf.ts

sh: wdio: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! appium-boilerplate@5.3.1 ios.app: `wdio ./config/wdio.ios.app.conf.ts`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the appium-boilerplate@5.3.1 ios.app script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Environment (please complete the following information):**
 - Node.js version: [Node.js v12.14.1]
 - NPM version: [6.13.4]
 - Platform: [MacOs Catalina]
 - Platform version: [10.15]
 - Emulator/Simulator/Real Device: [Simulator]

**Comment by christian-bromann** [comment]
> sh: wdio: command not found

Please make sure you have installed the dependencies via `npm install`

**Comment by stasek513** [comment]
Yes I did npm install and still the same error

**Comment by christian-bromann** [comment]
In this case you should find a `wdio` binary in `node_modules/.bin`. Can you confirm?

**Comment by stasek513** [comment]
Yes I have 
![Screenshot 2021-07-19 at 16 43 42](https://user-images.githubusercontent.com/87655200/126178753-782df17f-b8a1-4f00-907d-e12886f886a4.png)

**Comment by stasek513** [comment]
a sorry in side node/.bin should be wdio?

**Comment by stasek513** [comment]
Interesting when I add to package.json  "@wdio/selenium-standalone-service": "7.6.0", then I see wdio in /.bin folder and start works Thanks @christian-bromann
