### ISSUE TITLE
dependency @wdio/cli is missing to execute tests

### ISSUE THREAD

**Issue by nils-hoyer** [webdriverio/appium-boilerplate#104]
**Environment (please complete the following information):**
 - NPM version: 6.14.10

**Describe the bug**
appium-boilerplate is not containing related dependency `@wdio/cli` to execute any tests from webdriverio

**To Reproduce**
1. open terminal
2. run `git clone https://github.com/webdriverio/appium-boilerplate.git` 
2. run `npm install`
3. setup Appium on my local machine
4. setup iOS on my local machine
5. make demo app available from ./apps/
5. run `npm run ios.app`
6. expected: the tests can be executed
7. given: command wdio not found

**Comment by wswebcreation** [comment]
Thanks @nils-hoyer 

Can you submit a PR for this 😄 ?

**Comment by nils-hoyer** [comment]
ofc!

**Comment by nils-hoyer** [comment]
https://github.com/webdriverio/appium-boilerplate/pull/106
