### ISSUE TITLE
Getting error while running test

### ISSUE THREAD

**Issue by RollerIn** [webdriverio/appium-boilerplate#108]
% npm run android.app -- --spec=tests/specs/app.webview.spec.ts

> appium-boilerplate@5.3.1 android.app
> wdio config/wdio.android.app.conf.ts "--spec=tests/specs/app.webview.spec.ts"

Assertion failed: (thread_id_key != 0x7777), function find_thread_id_key, file ../src/coroutine.cc, line 134.
zsh: abort      npm run android.app -- --spec=tests/specs/app.webview.spec.ts

while running any test am getting th above error.

My requirement is : need to automate react app on mobile web browser 
can you assist me to run and check the feasibility of this framework?

**Comment by christian-bromann** [comment]
> Assertion failed: (thread_id_key != 0x7777), function find_thread_id_key, file ../src/coroutine.cc, line 134.

It seems you are running Node.js v16 with WebdriverIO in sync mode. We don't support this combination. Please run with a lower Node.js version or transform the code to run without `@wdio/sync` package. Read more about this in the [recent blog post](https://webdriver.io/blog/2021/07/28/sync-api-deprecation).
