### ISSUE TITLE
Convert project to async mode

### ISSUE THREAD

**Issue by EthanOrlander** [webdriverio/appium-boilerplate#110]
WebdriverIO recommends [here](https://webdriver.io/docs/sync-vs-async/#how-to-enabledisable-sync-mode) that you do not start a new project with sync mode anymore, as it is not supported in upcoming Chromium releases. I can go ahead and make a PR converting this project to async mode. Just want the go-ahead

**Comment by christian-bromann** [comment]
Yes, this move is necessary. If you want to help us out, please go ahead! Thanks a lot.

**Comment by wswebcreation** [comment]
Done
