### ISSUE TITLE
Parallel execution 

### ISSUE THREAD

**Issue by RollerIn** [webdriverio/appium-boilerplate#112]
Hello @wswebcreation

Can you add a feature of parallel execution for the following combinations?
Run test suites on android different browsers like 'chrome','firefox','Edge'
Run test suites on android on same browser like chrome ,…

same way for iOS

it could help us to implement in our framework.

Thanks In Advance.

**Comment by wswebcreation** [comment]
Hi @RollerIn 

Appium only officially support Chrome on Android and Safari on iOS. Firefox support is possible on Android, but has a lot of challenges for supporting this in a pipeline, see also the docs [here](https://github.com/appium/appium-geckodriver).

For now it doesn't have my focus, but feel free to create an example with docs on how to do this
