### ISSUE TITLE
Troubles with running tests locally on android simulator

### ISSUE THREAD

**Issue by vparlah** [webdriverio/appium-boilerplate#116]
**Environment:**
 - Node.js version: [14.17.3]
 - NPM version: [6.14.13]
 - Platform: [Android]
 - Platform version: [11]
 - Emulator/Simulator/Real Device: [Emulator]

**Describe the bug**
I was facing troubles when tried to run android tests
```
 username@macbook:~/Documents/Learning/appium-boilerplate|main⚡ ⇒ npm run android.app

> appium-boilerplate@5.3.1 android.app /Users/username/Documents/Learning/appium-boilerplate
> wdio config/wdio.android.app.conf.ts

sh: wdio: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! appium-boilerplate@5.3.1 android.app: `wdio config/wdio.android.app.conf.ts`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the appium-boilerplate@5.3.1 android.app script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/username/.npm/_logs/2021-10-03T07_49_36_843Z-debug.log

```

**Additional context**
It resolved when I added `"@wdio/cli": "^7.13.0",` dependency. Was that intended or I missed something with the default config?

**Comment by abubakar-pointivo** [comment]
It same issue I was facing.

**Comment by christian-bromann** [comment]
@wswebcreation `@wdio/cli` should be added to the package.json, no?

**Comment by wswebcreation** [comment]
hmm, stupid of me, I'll create a PR. I wonder why this didn't happen on my machine when I was developing this boilerplate

**Comment by wswebcreation** [comment]
It should be fixed now, please pull the latest `main`

**Comment by abubakar-pointivo** [comment]
Thanks @wswebcreation.  I think on your machine it was using global @wdio/cli package.
