### ISSUE TITLE
Is Appium-boilerplate needed for webdriverio Appium 

### ISSUE THREAD

**Issue by AhmedBahgat** [webdriverio/appium-boilerplate#120]
**I have a problem to setup WebdriverIO with Appium for mobile testing so 
Is appium-boilerplate is needed for testing mobile applications through webdriverIO?**

**Environment (please complete the following information):**
 - Node.js version: [17.3.0]
 - NPM version: [8.3.0]
 - Platform: [Android]
 - Platform version: [11.0]
 - Emulator/Simulator/Real Device: [Emulator]

**Comment by christian-bromann** [comment]
> **Is appium-boilerplate is needed for testing mobile applications through webdriverIO?**

No, it is just an example project how testing on mobile can look like. Let me know if you have further questions.
