### ISSUE TITLE
I can't run local android test

### ISSUE THREAD

**Issue by anggastika** [webdriverio/appium-boilerplate#124]
Hello, 
I have done :
- clone repo (master branch)
- put Android-NativeDemoApp-0.4.0.apk on folder ./apps
- run npm install
- trial run "npm run android.app"  

But : 
<img width="720" alt="Screen Shot 2022-03-11 at 14 54 34" src="https://user-images.githubusercontent.com/4958745/157856938-2348f802-f6c5-4a0d-874c-1a4d77662058.png">

This is My wdio.android.app.conf.ts
```
import { join } from 'path';
import config from './wdio.shared.local.appium.conf';

// ============
// Specs
// ============
config.specs = [
    './tests/specs/**/app*.spec.ts',
];

// ============
// Capabilities
// ============
// For all capabilities please check
// http://appium.io/docs/en/writing-running-appium/caps/#general-capabilities
config.capabilities = [
    {
        // The defaults you need to have in your config
        platformName: 'Android',
        maxInstances: 1,
        // For W3C the appium capabilities need to have an extension prefix
        // http://appium.io/docs/en/writing-running-appium/caps/
        // This is `appium:` for all Appium Capabilities which can be found here
        'appium:deviceName': 'device',
        //'appium:udid' : 'emulator-5554',
        'appium:platformVersion': '11.0',
        'appium:orientation': 'PORTRAIT',
        'appium:automationName': 'UiAutomator2',
        // The path to the app
        'appium:app': join(process.cwd(), './apps/Android-NativeDemoApp-0.4.0.apk'),
        // @ts-ignore
        'appium:appWaitActivity': 'com.wdiodemoapp.MainActivity',
        // Read the reset strategies very well, they differ per platform, see
        // http://appium.io/docs/en/writing-running-appium/other/reset-strategies/
        'appium:noReset': true,
        'appium:newCommandTimeout': 240,
    },
];

exports.config = config;

```

**Environment (please complete the following information):**
 - Node.js version: [17.6.0]
 - NPM version: [8.5.1]
 - Platform: [Android]
 - Platform version: [11.0]
 - Appium Desktop version : [1.22.x]
 - Emulator/Simulator/Real Device:  [Emulator]

Please help and give me best practice to run test

Thank You

**Comment by christian-bromann** [comment]
Can you provide some logs that WebdriverIO generates?

**Comment by anggastika** [comment]
How to generate logs from WebdriverIO ? sorry I am newbie 

@christian-bromann

**Comment by samaysimantbarik** [comment]
Hi Team,

I am facing the same problem as well. My node version is 16*

![image](https://user-images.githubusercontent.com/44022711/169248755-ce5953b6-bd0e-4b90-a54b-81838ebf3e15.png)

**Comment by christian-bromann** [comment]
> I am facing the same problem as well. My node version is 16*

Have you looked into the wdio logs what the issue could be?

**Comment by samaysimantbarik** [comment]
Hi  @christian-bromann ,

Now it's running. I ran the appium server locally and all good now. may be the appium-service isn't able to spin up the server.
Had to add this line : 
![image](https://user-images.githubusercontent.com/44022711/169250944-41a99d3f-289a-41f5-8645-56cda99b6007.png)

However, I am interested to know how the context switching works as I am facing similar issue on my repo, unfortunately this repo is also giving me same error.
![image](https://user-images.githubusercontent.com/44022711/169251279-c5ca6017-bc2a-4b38-8a45-f12a6d7c4d1a.png)

Wondering if this works on your system.

**Comment by christian-bromann** [comment]
Maybe Appium expects Chromedriver to be available in your `$PATH` or the Chromedriver you have has an invalid version.

**Comment by samaysimantbarik** [comment]
Okay, That may be the thing. In that case, could you update the Readme with this info.

**Comment by christian-bromann** [comment]
> could you update the Readme with this info

Well I am not quite sure which scenario applies here. If you know please go ahead and raise a PR with a docs fix. Thank you!

**Comment by wswebcreation** [comment]
There are two things here @samaysimantbarik 
You added a basePath option in your config, that is not needed because WDIO and the Appium service start with basePath `/` instead of `/wd/hub`
Secondly, Appium comes with the latest version of ChromeDriver, but your devices/emulator could have an older version of Chrome (Chrome and ChromeDriver versions are tied together). Appium can automatically determine the version of ChromeDriver it needs to have and also download it for you if you let is automatically download it for you, that's why you need to start the Appium Server with `relaxedSecurity: true`

**Comment by christian-bromann** [comment]
I'ld suggest to create a FAQ document and document these issues with their solutions, then we can close this issue.

**Comment by wswebcreation** [comment]
It's in here @christian-bromann https://github.com/webdriverio/appium-boilerplate#automating-chrome-or-safari

**Comment by christian-bromann** [comment]
There is no information about this `relaxedSecurity` thingy. Again, thinking about how we can close the issue I thought maybe we create a FAQ and document some of these problem solutions. Maybe folks will stumble upon this through Google. I just wonder what's left for us to do here?!

**Comment by samaysimantbarik** [comment]
Hi @wswebcreation ,

Thanks for your response. I am using the latest version of everything( Appium, emulator and chrome).
Still, if I don't explicitly install chromedriver and specify the path, my tests are failing, even with relaxed security.

My service definition:
![image](https://user-images.githubusercontent.com/44022711/169422370-7d1b96c0-e631-4c83-96d5-4c984d620e64.png)

Desired caps:
![image](https://user-images.githubusercontent.com/44022711/169422431-e2ecd772-f123-4b31-9c79-7ad1aca68ab7.png)

If I remove the chromeDriverExecutablePath, then I get the error, "No chromedriver ..... " .

Can you run the current master against latest appium and emulators(chrome 101) and check if you aren't getting any errors.

Thanks,
Samay

**Comment by wswebcreation** [comment]
Hi @samaysimantbarik 

Can you run your test with

```js
config.services = (config.services ? config.services : []).concat([
    [
        "appium",
        {
            // This will use the globally installed version of Appium
            command: "appium",
            args: {
                // This is needed to tell Appium that we can execute local ADB commands
                // and to automatically download the latest version of ChromeDriver
                relaxedSecurity: true,
                address: "localhost",
                log: "./appium.log",
            },
        },
    ],
]);
```

and share the `appium.log` file in a Gist. I want to see what is happening there because it works on my machine (sorry to say that)

**Comment by samaysimantbarik** [comment]
Hi @wswebcreation ,

Thanks heaps.

The above works like a charm.

A quick question: Do we have a generic way that works on existing and new appium server ?

The above snippet spins up an appium server and works great for execution.

However, if I want to use Appium inspector and for that I need to use the local appium desktop server, this setup complains.

Log:
`2022-05-23 03:22:20:826 [Appium] Welcome to Appium v1.22.3
2022-05-23 03:22:20:827 [Appium] Non-default server args:
2022-05-23 03:22:20:827 [Appium]   address: localhost
2022-05-23 03:22:20:827 [Appium]   basePath: /
2022-05-23 03:22:20:828 [Appium]   logFile: ./appium.log
2022-05-23 03:22:20:828 [Appium]   relaxedSecurityEnabled: true
2022-05-23 03:22:20:852 [HTTP] Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.
`

**Comment by wswebcreation** [comment]
Hi @samaysimantbarik 

Thanks for your response, but what did you change to make it work now? Your code and my code look the same, except for the `log`-property.

The new Appium Inspector uses a different basePath then a normal Appium server (Appium 1.x versions) would spin up. By default Appium Server uses `/wd/hub/`, but it needs to be `/`. 
If you've installed Appium **globally** then you can then start a server with this

```bash
appium --base / --relaxed-security --log-timestamp
```

Where:
- `appium` is the _start_-server command
- `--base /` tells Appium to use `/` instead of the default `/wd/hub` basePath
- `--relaxed-security` means to automatically download the ChromeDriver (amongst other things, see [this](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/security.md#security-server-args))
- `--log-timestamp` adds a nice timestamp to the logs

Running this will give this give the following logs

```logs
appium --base / --relaxed-security --log-timestamp
2022-05-23 05:17:02:697 - [Appium] Welcome to Appium v1.22.3
2022-05-23 05:17:02:699 - [Appium] Non-default server args:
2022-05-23 05:17:02:699 - [Appium]   basePath: /
2022-05-23 05:17:02:700 - [Appium]   logTimestamp: true
2022-05-23 05:17:02:700 - [Appium]   relaxedSecurityEnabled: true
2022-05-23 05:17:02:725 - [Appium] Appium REST http interface listener started on 0.0.0.0:4723
```

As you can see it will automatically start on port 4723, also the port that Appium Inspector uses.

I'm going to close this issue now because this is not related to this boilerplate anymore, but it's still open for conversation

**Comment by muhammedInan** [comment]
I'd like to reopen the ticket because I'm having the same problem, even though I've tried your solutions and the error persists. 

exports.config = {
    //
    // ====================
    // Runner Configuration
    // ====================
    // WebdriverIO supports running e2e tests as well as unit and component tests.
    runner: 'local',

   // port: 4723,
    //
    // ==================
    // Specify Test Files
    // ==================
    // Define which test specs should run. The pattern is relative to the directory
    // of the configuration file being run.
    //
    // The specs are defined as an array of spec files (optionally using wildcards
    // that will be expanded). The test for each spec file will be run in a separate
    // worker process. In order to have a group of spec files run in the same worker
    // process simply enclose them in an array within the specs array.
    //
    // If you are calling `wdio` from an NPM script (see https://docs.npmjs.com/cli/run-script),
    // then the current working directory is where your `package.json` resides, so `wdio`
    // will be called from there.
    //
    specs: [
        './features/Android/*.feature'
    ],
    exclude: [
        // 'path/to/excluded/files'
    ],
    //
    // ============
    // Capabilities
    // ============
    // Define your capabilities here. WebdriverIO can run multiple capabilities at the same
    // time. Depending on the number of capabilities, WebdriverIO launches several test
    // sessions. Within your capabilities you can overwrite the spec and exclude options in
    // order to group specific specs to a specific capability.
    //
    // First, you can define how many instances should be started at the same time. Let's
    // say you have 3 different capabilities (Chrome, Firefox, and Safari) and you have
    // set maxInstances to 1; wdio will spawn 3 processes. Therefore, if you have 10 spec
    // files and you set maxInstances to 10, all spec files will get tested at the same time
    // and 30 processes will get spawned. The property handles how many capabilities
    // from the same test should run tests.
    //
    maxInstances: 10,
    //
    // If you have trouble getting all important capabilities together, check out the
    // Sauce Labs platform configurator - a great tool to configure your capabilities:
    // https://saucelabs.com/platform/platform-configurator
    //
    capabilities: [{
        'appium:acceptInsecureCerts': true,
        "appium:platformName": "Android",
        "appium:platformVersion": "10",
        "appium:deviceName": "deviceId",
        'appium:app': '...apk',
        'appium:appPackage': 'app',
        'appium:appActivity': 'Launch',
        'appium:automationName': 'UiAutomator2',
        'appium:language': 'en',
        'appium:locale': 'UK',
        'appium:newCommandTimeout': 240,
        'appium:fullReset': true,
        'appium:autoAcceptAlerts': true,
        'appium:autoGrantPermissions': true,
        'appium:deviceOrientation': 'portrait',
        'appium:unicodeKeyboard': true,
        'appium:resetKeyboard': true,
        'appium:ignoreHiddenApiPolicyError': true,
        'appium:fullContextList': true,
        'appium:networkSpeed': 'full',
        'appium:chromedriverExecutableDir': './node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/',
         'appium:chromeOptions': {
             args: [
                 '--disable-popup-blocking',
                 '--disable-notifications'
             ],
             'w3c': false
         },
    }, ],
    //
    // ===================
    // Test Configurations
    // ===================
    // Define all options that are relevant for the WebdriverIO instance here
    //
    // Level of logging verbosity: trace | debug | info | warn | error | silent
    logLevel: 'info',
    //
    // Set specific log levels per logger
    // loggers:
    // - webdriver, webdriverio
    // - @wdio/browserstack-service, @wdio/devtools-service, @wdio/sauce-service
    // - @wdio/mocha-framework, @wdio/jasmine-framework
    // - @wdio/local-runner
    // - @wdio/sumologic-reporter
    // - @wdio/cli, @wdio/config, @wdio/utils
    // Level of logging verbosity: trace | debug | info | warn | error | silent
    // logLevels: {
    //     webdriver: 'info',
    //     '@wdio/appium-service': 'info'
    // },
    //
    // If you only want to run your tests until a specific amount of tests have failed use
    // bail (default is 0 - don't bail, run all tests).
    bail: 0,
    //
    // Set a base URL in order to shorten url command calls. If your `url` parameter starts
    // with `/`, the base url gets prepended, not including the path portion of your baseUrl.
    // If your `url` parameter starts without a scheme or `/` (like `some/path`), the base url
    // gets prepended directly.
    baseUrl: 'http://localhost',
    //
    // Default timeout for all waitFor* commands.
    waitforTimeout: 12000,
    //
    // Default timeout in milliseconds for request
    // if browser driver or grid doesn't send response
    connectionRetryTimeout: 120000,
    //
    // Default request retries count
    connectionRetryCount: 3,
    //
    // Test runner services
    // Services take over a specific job you don't want to take care of. They enhance
    // your test setup with almost no effort. Unlike plugins, they don't add new
    // commands. Instead, they hook themselves up into the test process.

    services: [
           [
           'appium',
           //'chromedriver',
            {
            command: "appium",
             args: {
               address: 'localhost',
               baseUrl: '/wd/hub',
               port: 4723,
               relaxedSecurity: true,
               log: "./appium.log",
            },
                
            },
    ],
    ],

//services: ['appium', 'chromedriver'],
    
   // services: ['appium'],
    // Framework you want to run your specs with.
    // The following are supported: Mocha, Jasmine, and Cucumber
    // see also: https://webdriver.io/docs/frameworks
    //
    // Make sure you have the wdio adapter package for the specific framework installed
    // before running any tests.
    framework: 'cucumber',
    //
    // The number of times to retry the entire specfile when it fails as a whole
    // specFileRetries: 1,
    //
    // Delay in seconds between the spec file retry attempts
    // specFileRetriesDelay: 0,
    //
    // Whether or not retried specfiles should be retried immediately or deferred to the end of the queue
    // specFileRetriesDeferred: false,
    //
    // Test reporter for stdout.
    // The only one supported by default is 'dot'
    // see also: https://webdriver.io/docs/dot-reporter
    reporters: ['spec'],

    cucumberOpts: {
        // <string[]> (file/dir) require files before executing features
        require: ['./step-definitions/Android/*.js'],
        // <boolean> show full backtrace for errors
        backtrace: false,
        // <string[]> ('extension:module') require files with the given EXTENSION after requiring MODULE (repeatable)
        requireModule: [],
        // <boolean> invoke formatters without executing steps
        dryRun: false,
        // <boolean> abort the run on first failure
        failFast: false,
        // <boolean> hide step definition snippets for pending steps
        snippets: true,
        // <boolean> hide source uris
        source: true,
        // <boolean> fail if there are any undefined or pending steps
        strict: false,
        // <string> (expression) only execute the features or scenarios with tags matching the expression
        tagExpression: '',
        // <number> timeout for step definitions
        timeout: 60000,
        // <boolean> Enable this config to treat undefined definitions as warnings.
        ignoreUndefinedDefinitions: false
    },

**Comment by muhammedInan** [comment]
the error in question 

ERROR webdriver: RequestError: connect ECONNREFUSED 127.0.0.1:4723
[0-0]     at ClientRequest.<anonymous> (file:///Users/qaicf/kara-automation/node_modules/got/dist/source/core/index.js:790:107)
[0-0]     at Object.onceWrapper (node:events:626:26)
[0-0]     at ClientRequest.emit (node:events:523:35)
[0-0]     at ClientRequest.emit (node:domain:489:12)
[0-0]     at Socket.socketErrorListener (node:_http_client:495:9)
[0-0]     at Socket.emit (node:events:511:28)
[0-0]     at Socket.emit (node:domain:489:12)
[0-0]     at emitErrorNT (node:internal/streams/destroy:151:8)
[0-0]     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:82:21)
[0-0]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1574:16)
[0-0] 2023-07-04T14:08:26.384Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] Unable to connect to "http://127.0.0.1:4723/", make sure browser driver is running on that address.
[0-0] If you use services like chromedriver see initialiseServices logs above or in wdio.log file as the service might had problems to start the driver.
