### ISSUE TITLE
I can't run local IOS test

### ISSUE THREAD

**Issue by zhengyanan1** [webdriverio/appium-boilerplate#125]
Hello,
I have done :

- clone repo (master branch)
- put XCUITestsDemo.ipa on folder ./apps
- run npm install
- run "npm run ios.app"

But I can't run ios test well, here is my wdio.ios.app.conf.ts
<img width="2017" alt="image" src="https://user-images.githubusercontent.com/16793425/160585940-4c9c9382-9fd9-4e3a-9c29-b6dfd1cc917d.png">

```
import { join } from 'path';
import config from './wdio.shared.local.appium.conf';

// ============
// Specs
// ============
config.specs = [
    './tests/specs/app-ios.openapp.spec.ts',
];

// ============
// Capabilities
// ============
// For all capabilities please check
// http://appium.io/docs/en/writing-running-appium/caps/#general-capabilities
config.capabilities = [
    {
        // The defaults you need to have in your config
        platformName: 'iOS',
        maxInstances: 1,
        logLevel: 'debug',
        // For W3C the appium capabilities need to have an extension prefix
        // This is `appium:` for all Appium Capabilities which can be found here
        // http://appium.io/docs/en/writing-running-appium/caps/
        'appium:deviceName': 'iPhone6sp',
        'appium:platformVersion': '10.0',
        'appium:orientation': 'PORTRAIT',
        'appium:automationName': 'XCUITest',
        // The path to the app
        'appium:app': join(process.cwd(), './apps/XCUITestsDemo.ipa'),
        // Read the reset strategies very well, they differ per platform, see
        // http://appium.io/docs/en/writing-running-appium/other/reset-strategies/
        'appium:noReset': true,
        'appium:newCommandTimeout': 240,
    },
];

exports.config = config;

```

**Environment :**
 - Node.js version: [v14.17.3]
 - NPM version: [6.14.13]
 - Platform: [IOS]
 - Platform version: [10.0.2]
 - Emulator/Simulator/Real Device: [Real Device]

**Additional context**
here is a npm error log in the below.
[2022-03-29T09_49_57_077Z-debug.log](https://github.com/webdriverio/appium-boilerplate/files/8370187/2022-03-29T09_49_57_077Z-debug.log).

please help me to run ios test

**Comment by christian-bromann** [comment]
@zhengyanan1 doesn't the error message clearly clarifies the problem? You've set `appium:platformVersion` to `10.0` but your system has not this version installed. You can either install it through XCode or pick a version that is installed like `14.4`.
