### ISSUE TITLE
Browserstack app capabilities no longer work with WDIO v7.20.0

### ISSUE THREAD

**Issue by SergeySc** [webdriverio/appium-boilerplate#129]
**Environment (please complete the following information):**
 - Node.js version: 16.14.2
 - NPM version: 8.7.0
 - Platform: Android
 - Platform version: 11.0
 - Emulator/Simulator/Real Device: Real Device

**Describe the bug**
Browserstack app capabilities no longer work after upgrading from wdio version 7.19.7 to 7.20.0 or later.
I have not made any changes in the framework, just updated the packages with `npm update`
When running tests with `npm run android.browserstack.app` i get the following error:
```
ERROR @wdio/runner: Error: Invalid or unsupported WebDriver capabilities fou
nd ("browserstack.debug", "app", "device", "os_version", "project", "build", "name"). Ensure to only use va
lid W3C WebDriver capabilities (see https://w3c.github.io/webdriver/#capabilities).If you run your tests on
 a remote vendor, like Sauce Labs or BrowserStack, make sure that you put them into vendor specific capabil
ities, e.g. "sauce:options" or "bstack:options". Please reach out to to your vendor support team if you hav
e further questions.
```

**To Reproduce**
Update packages with `npm update`.
This should get wdio to 7.20.2 (at this time).
Then run tests with `npm run android.browserstack.app`

**Expected behavior**
Connection to browserstack is made and tests are running.

**Comment by christian-bromann** [comment]
Non of the changes related to the v7.20.0 release were responsible for this change. The capability restriction was introduced with the v7 major release. As the error states please use valid W3C capabilities, meaning put all caps listed in the error message into a `bstack:options` object. For support please reach out to the BS support team or the WebdriverIO Gitter channel. Thanks!
