### ISSUE TITLE
fingerPrint(fingerprintid) is not working

### ISSUE THREAD

**Issue by vasudha0309** [webdriverio/appium-boilerplate#130]
**Environment (please complete the following information):**
 - Node.js version: 12.16.1
 - NPM version: 6.13.4
 - Platform: Android
 - Platform version: 11
 - Emulator/Simulator/Real Device: Emulator

**Describe the bug**
I'm trying to run an automation code using webdriverio and appium on android device. Fingerprint is enabled in the emulator, and device can be unlocked using a fingerprint ( from emulator settings).

When I'm running code as follows -
driver.lock();
driver.fingerPrint(1);

This isn't unlocking the device as expected. 
Ran the biometric spec in the boilerplate project and fingerprint is not working there as well.

Can someone please confirm if this is a bug or an error in implementation?

**Comment by christian-bromann** [comment]
> Can someone please confirm if this is a bug or an error in implementation?

Can you see the command being send to Appium in the Appium logs? If so I would report the problem in Appium rather than here.

**Comment by vasudha0309** [comment]
Oh yes post call is being made to appium server. So this is an appium issue not with wdio?

**Comment by christian-bromann** [comment]
> So this is an appium issue not with wdio?

Correct, closing then.

**Comment by vasudha0309** [comment]
I had enabled the fingerprint manually through emulator settings. I used the fingerprints in emulator i.e. Finger 1, and was sending the id as 1.
When i setup according to the test case you mentioned, the fingerPrintid was just the pin that is set when enabling biometrics. 
So this will work when fingerprint is enabled using script only?

**Comment by wswebcreation** [comment]
AFAIK know yes
