### ISSUE TITLE
Does this boilerplate use jasmine or mocka?

### ISSUE THREAD

**Issue by kopax-polyconseil** [webdriverio/appium-boilerplate#136]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/native-demo-app) and submit a pull request

**Describe the improvement**

I'd like to report
- [x] Unclear documentation
- [ ] A typo
- [ ] Missing documentation
- [ ] Other

**Description of the improvement / report**

I am a jest user and discover mocka and jasmine and I am a bit confused with what we have here, let me explain: 

- In the configuration, it use the framework `mocka`: https://github.com/webdriverio/appium-boilerplate/blob/main/config/wdio.shared.conf.ts#L94-L100

- In the documentation, it says: 

![image](https://user-images.githubusercontent.com/77674046/200419828-a566fdcf-4a4a-4ccf-8f24-197ab53cbfc8.png)

> This boilerplate includes the following:
> 
> Framework: Jasmine

Source https://webdriver.io/docs/boilerplates/

**Comment by christian-bromann** [comment]
This boilerplate as you correctly pointed out uses Moc__h__a. I updated the docs to reflect this correctly.
