### ISSUE TITLE
webdriverio/appium/android app  question - how to press back button on Android device?

### ISSUE THREAD

**Issue by chinhnguyen8855** [webdriverio/appium-boilerplate#14]
**Describe your question with as much detail as possible**
I would like to automate a step to press on the Back button (or any buttons) of an Android device.  I tried following options but none of them work.  Could you please help?

1. Call "browser.pressKeyCode(4).  Error throws "browser.pressKeyCode is not a function"

2.  Call "driver.pressKeyCode(4)".  Error throws "driver is not defined"

Appium 1.9.1
webdriverio version 4

**If it's about a specific piece of code, try and include some of it to support your question.**
Here is my config

capabilities: [{
    "platformName": "Android",
    "app": "/Users/app/build/outputs/apk/debug/app-debug.apk",
    "deviceName": "Pixel_API_27_8.1",
    "platformVersion": "8.1",
    "noReset": true,
    "appWaitActivity": "com.xxxx.cloud.mobile.onboarding.launchscreen.LaunchScreenActivity",
    "appActivity": ".logon.LogonActivity",
    "automationName": "UiAutomator2",
    "avd": "Pixel_API_27_8.1"
}],

**Environment (please complete the following information):**
 - Node.js version: 8.12
 - NPM version: 6.4.1
 - Platform: Android
 - Platform version: 8.1
 - Emulator/Simulator/Real Device: Emulator

**Additional context**

**Comment by christian-bromann** [comment]
If you use WebdriverIO v4 please see http://v4.webdriver.io/api/mobile/pressKeycode.html

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
