### ISSUE TITLE
Update dependencies to use v8

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/appium-boilerplate#145]
We just released WebdriverIO v8 and should update the boilerplate to use the new version.

**Comment by kopax-polyconseil** [comment]
Hello, I was just checking if a v8 example conf was here because it seems not to be straightforward upgrade

**Comment by christian-bromann** [comment]
> Hello sir, any update on this please.

As you can see, there are no updates, feel free to get involved and help us update the boilerplate, thanks!

**Comment by christian-bromann** [comment]
Done in https://github.com/webdriverio/appium-boilerplate/commit/7ddf4b6aa091b706ae24acd166dbd588c3d0c4ad .. we still would appreciate more help maintaining this repository.
