### ISSUE TITLE
How we can upgrade this project to v8?

### ISSUE THREAD

**Issue by rajivnw** [webdriverio/appium-boilerplate#149]
I updated this project dev dependencies to newer version using npm outdated and then npm update/ install with latest versions.

In tsconfig.json I set the target :ES2018 and module : ES2022. Also set "type":"module" in package.json.

When I run for example android.wdio.ts file. I get an error like-
Error @wdio/config:ConfigParser: failed to loading configuration files : file:///[my_local_system_path]
CustmError: cannot find module 'xxxxxxx' even this module is exist and by pressing ctrl+click I can navigate.

Main reason to upgrade is, I am looking to use top label await in wdio config file and as per my understanding  this is possible when we use latest ES version in targe and module in tsconfig file and add type as a module in package.json.

Also, I check that the cucumber boilerplate project is running on v8. But when I added config folder and copy the wdio files from this project to cucumber project, same error I am getting.

Can you please suggest I can upgrade this project to v8 so I can set the target :ES2018 and module : ES2022 in tsconfig.json. Also set "type":"module" in package.json?

**Comment by christian-bromann** [comment]
We are already tracking updating the boilerplate to v8 in #145. Any contributions to would be appreciated thanks.

> Can you please suggest I can upgrade this project to v8 so I can set the target :ES2018 and module : ES2022 in tsconfig.json. Also set "type":"module" in package.json?

I don't have an answer to this on top of my head without working through the process of updating the deps myself.
