### ISSUE TITLE
No Spec Found To Run

### ISSUE THREAD

**Issue by MaganAnkur** [webdriverio/appium-boilerplate#152]
**Environment (please complete the following information):**
 - Node.js version: 16.16.0
 - NPM version: 8.11.0
 - Platform: Android
 - Platform version: 11
 - Emulator/Simulator/Real Device: Emulator

**Describe the bug**
after setting up the boilerplate I am trying to run the android test using `npm run android.app`, but it always gives **Spec Not Found** error.

**To Reproduce**
I have cloned appium-boilerplate

**Expected behavior**
all test should run

**Screenshots**
`Android Config`
<img width="1091" alt="Screenshot 2023-01-26 at 9 53 30 AM" src="https://user-images.githubusercontent.com/42070594/214867764-5654fc67-d1ec-49b8-9e9b-126c257a1e53.png">
`Project Structure`
<img width="682" alt="Screenshot 2023-01-26 at 9 53 53 AM" src="https://user-images.githubusercontent.com/42070594/214867863-32b24afc-44a6-402e-838c-1cd0c09484cb.png">
`Error Logs`
<img width="965" alt="Screenshot 2023-01-26 at 9 55 03 AM" src="https://user-images.githubusercontent.com/42070594/214868286-97ca495e-cd51-4b08-ae55-d7bf9e5552cf.png">

**Additional context**

**Comment by MaganAnkur** [comment]
@christian-bromann your help is greatly appreciated, thanks

**Comment by christian-bromann** [comment]
Your `wdio.conf.ts` is in the `./config` directory while your spec pattern is `./tests/specs/...`. Since v8 the spec pattern has to be relative to the config file so you have to update that.

**Comment by MaganAnkur** [comment]
thanks @christian-bromann , it worked closing this,
By any chance would you be able to help if how can I get .app file from App Center
