### ISSUE TITLE
not possibility to run in local Android 

### ISSUE THREAD

**Issue by muhammedInan** [webdriverio/appium-boilerplate#157]
I'd like to open the ticket because I'm having the problem to run in local . 

exports.config = {
runner: 'local',
port: 4723,
specs: [
    './features/Android/*.feature'
],
exclude: [
    // 'path/to/excluded/files'
],
maxInstances: 10,
capabilities: [{
    'appium:acceptInsecureCerts': true,
    "appium:platformName": "Android",
    "appium:platformVersion": "10",
    "appium:deviceName": "deviceId",
    'appium:app': '...apk',
    'appium:appPackage': 'app',
    'appium:appActivity': 'Launch',
    'appium:automationName': 'UiAutomator2',
    'appium:language': 'en',
    'appium:locale': 'UK',
    'appium:newCommandTimeout': 240,
    'appium:fullReset': true,
    'appium:autoAcceptAlerts': true,
    'appium:autoGrantPermissions': true,
    'appium:deviceOrientation': 'portrait',
    'appium:unicodeKeyboard': true,
    'appium:resetKeyboard': true,
    'appium:ignoreHiddenApiPolicyError': true,
    'appium:fullContextList': true,
    'appium:networkSpeed': 'full',
    'appium:chromedriverExecutableDir': './node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/',
     'appium:chromeOptions': {
         args: [
             '--disable-popup-blocking',
             '--disable-notifications'
         ],
         'w3c': false
     },
}, ],

logLevel: 'info',
//

// - webdriver, webdriverio
// - @wdio/browserstack-service, @wdio/devtools-service, @wdio/sauce-service
// - @wdio/mocha-framework, @wdio/jasmine-framework
// - @wdio/local-runner
// - @wdio/sumologic-reporter
// - @wdio/cli, @wdio/config, @wdio/utils
// Level of logging verbosity: trace | debug | info | warn | error | silent
// logLevels: {
//     webdriver: 'info',
//     '@wdio/appium-service': 'info'
// },

bail: 0,

baseUrl: 'http://localhost',

waitforTimeout: 12000,

connectionRetryTimeout: 120000,

connectionRetryCount: 3,

services: [
       [
       'appium',
       //'chromedriver',
        {
        command: "appium",
         args: {
           address: 'localhost',
           baseUrl: '/wd/hub',
           port: 4723,
           relaxedSecurity: true,
           log: "./appium.log",
        },
            
        },
],
],

//services: ['appium', 'chromedriver'],

framework: 'cucumber',

// specFileRetries: 1,

// specFileRetriesDelay: 0,

reporters: ['spec'],

cucumberOpts: {
    // <string[]> (file/dir) require files before executing features
    require: ['./step-definitions/Android/*.js'],
    // <boolean> show full backtrace for errors
    backtrace: false,
    // <string[]> ('extension:module') require files with the given EXTENSION after requiring MODULE (repeatable)
    requireModule: [],
    dryRun: false,
    failFast: false,
    snippets: true,
    source: true,
    strict: false,
    tagExpression: '',
    timeout: 60000,
    ignoreUndefinedDefinitions: false
},

the error in question
ERROR webdriver: RequestError: connect ECONNREFUSED 127.0.0.1:4723 [0-0] at ClientRequest. (file:///Users/qaicf/kara-automation/node_modules/got/dist/source/core/index.js:790:107) [0-0] at Object.onceWrapper (node:events:626:26) [0-0] at ClientRequest.emit (node:events:523:35) [0-0] at ClientRequest.emit (node:domain:489:12) [0-0] at Socket.socketErrorListener (node:_http_client:495:9) [0-0] at Socket.emit (node:events:511:28) [0-0] at Socket.emit (node:domain:489:12) [0-0] at emitErrorNT (node:internal/streams/destroy:151:8) [0-0] at emitErrorCloseNT (node:internal/streams/destroy:116:3) [0-0] at processTicksAndRejections (node:internal/process/task_queues:82:21) [0-0] at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1574:16) [0-0] 2023-07-04T14:08:26.384Z ERROR @wdio/runner: Error: Failed to create session. [0-0] Unable to connect to "http://127.0.0.1:4723/", make sure browser driver is running on that address. [0-0] If you use services like chromedriver see initialiseServices logs above or in wdio.log file as the service might had problems to start the driver.

I use Appium version 1.22.3 and MacBook Air M1

**Comment by christian-bromann** [comment]
> Unable to connect to "http://127.0.0.1:4723/", make sure browser driver is running on that address.

This error tells that you haven't started Appium on port `4723`. Can you provide more WDIO logs?

**Comment by rajivnw** [comment]
remove address: 'localhost' from args.  It may solve this issue.

**Comment by christian-bromann** [comment]
Thanks @rajivnw .. I will close the issue. Let me know if any further question come up.
