### ISSUE TITLE
Problem in Webview screen about chromedriver

### ISSUE THREAD

**Issue by muhammedInan** [webdriverio/appium-boilerplate#158]
I'm having a problem at the webview stage, I'm getting an error even though I've correctly specified the path to the chromedriver file. I use Appium 1.22 version

exports.config = {
runner: 'local',
port: 4723,
specs: [
    './features/Android/*.feature'
],
exclude: [
    // 'path/to/excluded/files'
],

maxInstances: 10,

capabilities: [{
    'appium:acceptInsecureCerts': true,
    "appium:platformName": "Android",
    "appium:platformVersion": "10",
    "appium:deviceName": "deviceId",
    'appium:app': '...apk',
    'appium:appPackage': 'app',
    'appium:appActivity': 'Launch',
    'appium:automationName': 'UiAutomator2',
    'appium:language': 'en',
    'appium:locale': 'UK',
    'appium:newCommandTimeout': 240,
    'appium:fullReset': true,
    'appium:autoAcceptAlerts': true,
    'appium:autoGrantPermissions': true,
    'appium:deviceOrientation': 'portrait',
    'appium:unicodeKeyboard': true,
    'appium:resetKeyboard': true,
    'appium:ignoreHiddenApiPolicyError': true,
    'appium:fullContextList': true,
    'appium:networkSpeed': 'full',
    'appium:chromedriverExecutableDir': './node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/',
     'appium:chromeOptions': {
         args: [
             '--disable-popup-blocking',
             '--disable-notifications'
         ],
         'w3c': false
     },
}, ],

logLevel: 'info',

// loggers:
// - webdriver, webdriverio

// logLevels: {
//     webdriver: 'info',
//     '@wdio/appium-service': 'info'
// },

bail: 0,

baseUrl: 'http://localhost',

waitforTimeout: 12000,

connectionRetryTimeout: 120000,

connectionRetryCount: 3,

services: [
       [
       'appium',
       'chromedriver',
        {
        command: "appium",
         args: {
           address: 'localhost',
           baseUrl: '/wd/hub',
           port: 4723,
           relaxedSecurity: true,
           log: "./appium.log",
        },         
        },
],
],

framework: 'cucumber',
// specFileRetries: 1,

// specFileRetriesDelay: 0,

reporters: ['spec'],

cucumberOpts: {
    // <string[]> (file/dir) require files before executing features
    require: ['./step-definitions/Android/*.js'],
    // <boolean> show full backtrace for errors
    backtrace: false,
    // <string[]> ('extension:module') require files with the given EXTENSION after requiring MODULE (repeatable)
    requireModule: [],
    dryRun: false,
    failFast: false,
    snippets: true,
    source: true,
    strict: false,
    tagExpression: '',
    timeout: 60000,
    ignoreUndefinedDefinitions: false
},

The error in question 

unknown error: An unknown server-side error occurred while processing the command. Original error: No Chromedriver found that can automate Chrome '114.0.5735'. You could also try to enable automated chromedrivers download server feature. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details

**Comment by christian-bromann** [comment]
Thanks for raising the issue.

It seems the error message is clear here. Please configure Chromedriver correctly so that Appium can automate Chrome. See provided URL for more information.

Happy to answer further questions.
