### ISSUE TITLE
Using for statement in spec file

### ISSUE THREAD

**Issue by vladimirtudor22** [webdriverio/appium-boilerplate#159]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/native-demo-app) and submit a pull request

**Describe the improvement**

I'd like to report
- [x] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [x] Other

**Description of the improvement / report**
A clear and concise description.
 
Hello, I have an issue with for statement in spec file, I need to test multiple items of a FlatList. I want to do a context who contain a for statement and run my "it" for item0,item1,item2, etc. Is that possible using this boilerplate? Is another solution?

**Comment by christian-bromann** [comment]
Join our  [Discord](https://discord.webdriver.io) server for these kind of questions. This is not necessary a WebdriverIO related issue.
