### ISSUE TITLE
Element selector on Android using resource-id

### ISSUE THREAD

**Issue by fergadipa** [webdriverio/appium-boilerplate#16]
Hi guys,

Thank you for provide us this Boilerplate project. I really appreciate it. I have read in 'Locator strategy for native apps' section in README.md that said 'The locator strategy for this boilerplate is to use accessibilityID's'.
I have read your code and I assume that element selector defined in screenobjects folder (for example: forms.screen.js)
```
const SELECTORS = {
    FORMS_SCREEN: '~Forms-screen',
    INPUT: '~text-input',
    INPUT_TEXT: '~input-text-result',
    SWITCH: '~switch',
    SWITCH_TEXT: '~switch-text',
    DROP_DOWN: '~select-Dropdown',
    ACTIVE_BUTTON: '~button-Active',
    IN_ACTIVE_BUTTON: '~button-Inactive',
};
```
What if using resource-id? How to define the selector? Is there any short way like accessibilityID?

Thank you.

**Environment (please complete the following information):**
 - Node.js version: 10.14.1
 - NPM version: 6.4.1
 - Platform: Android
 - Platform version: 7.1.2
 - Emulator/Simulator/Real Device: Real Device

**Comment by wswebcreation** [comment]
Hi @fergadipa 

I'd like to refer you to https://webdriver.io/docs/selectors.html#mobile-selectors where all the mobile selectors are explained, or join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions.
