### ISSUE TITLE
Request resetBetweenTest config

### ISSUE THREAD

**Issue by fergadipa** [webdriverio/appium-boilerplate#17]
Hi there :)

**Problem description:**
I am exploring this project and find the noReset on the config. I found that config only affect between test file, not between every testcase run. I have tried using driver.reset() in beforeEach and also tried in afterEach, it works on the app but in the console the execution time never stop.

**Describe the solution you'd like**

**Describe alternatives you've considered**
In order to make every testcase should be independent (one test have no dependency on another test/previous test), I would like to propose something configuration like resetBetweenTest.

Thank you very much, this project really help my work :)

**Comment by simongilmurray** [comment]
@fergadipa Try going to the respective config file (e.g. /config/wdio.ios.app.conf.js for iOS)

Remove the following flag (or set it to False):

`noReset: true`

Each run should now reset the App.

**Comment by wswebcreation** [comment]
@fergadipa 

Sorry for the late response, been packed with work currently. Have you tried what @simongilmurray said?

**Comment by wswebcreation** [comment]
Going to close this issue due to inactivity
