### ISSUE TITLE
Activate mobile testing pipelines

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/appium-boilerplate#187]
**Is your feature request related to a problem? Please describe.**
We got a contribution that would enable mobile native tests in GitHub CI to ensure that changes in the boilerplate are tested in real environments. Unfortunately we never been able to activate them.

**Describe the solution you'd like**
Let's make sure to enable all pipelines and have some solid e2e tests in place that also help users find out how to setup mobile tests in Github Actions.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by wswebcreation** [comment]
Closing this one because this has already been implemented
