### ISSUE TITLE
Cannot run Android tests from appium-boilerplate project

### ISSUE THREAD

**Issue by sergiybuch** [webdriverio/appium-boilerplate#20]
**Environment:**
 - Node.js version: [e.g. 10.15.1]
 - NPM version: [e.g. 6.8.0]
 - Platform: Android
 - Platform version: 8.1.0 / 7.1.1
 - Simulator/Real Device: Same behavior on both

**Describe the bug**
I set up this project and when I am trying to run the Android tests, app starts for a moment and then crashes. It happens on both, Real and virtual devices. Logs in appium server saying: 
"[debug] [W3C] Encountered internal error running command: Error: The instrumentation process cannot be initialized. Make sure the application under test does not crash and investigate the logcat output."

When I open app manually on AVD/Real Device it works fine.

**Screenshots**
![appium](https://user-images.githubusercontent.com/28896994/53498422-52b93e80-3a74-11e9-8cf7-25c8da026b2c.gif)

Appium Server logs
[Appium Logs.txt](https://github.com/webdriverio/appium-boilerplate/files/2910737/Appium.Logs.txt)

**Comment by wswebcreation** [comment]
Hi @sergiybuch 

Thanks for mentioning. I'll check it and come back to you on it.

**Comment by wswebcreation** [comment]
Hi @sergiybuch 

I've been looking into this and I have a typical answer for you. It works on my machine 😉 . 
Just kidding, the diff in our setup is that I'm using a Mac and you are using a Windows machine.

What happens if you install the app manually and start it, will it still crash?
And did you also try this with a different app?

**Comment by muralidey** [comment]
I'm seeing similar issue with GalaxyS8+ with my App. When I run the code when mobile connected to my laptop it works. Sooner I move it to the grid environment, I am getting following error 

[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.11.1"}}
[HTTP] <-- GET /wd/hub/status 200 2 ms - 68
[HTTP] 
[UiAutomator2] Waiting up to 30000ms for UiAutomator2 to be online...
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","ce11171b2906892104","shell","am","instrument","-w","io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner"]
[debug] [Instrumentation] io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:
[debug] [Instrumentation] INSTRUMENTATION_RESULT: shortMsg=Process crashed.
[debug] [Instrumentation] INSTRUMENTATION_CODE: 0
[debug] [Instrumentation] The process has exited with code 0
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.11.1"}}
[HTTP] <-- GET /wd/hub/status 200 2 ms - 68
[HTTP] 
[UiAutomator2] Error: The instrumentation process cannot be initialized. Make sure the application under test does not crash and investigate the logcat output.
[UiAutomator2]     at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[UiAutomator2]     at UiAutomator2Server.startSession (/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/uiautomator2.js:196:13)
[UiAutomator2]     at <anonymous>
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session

**Comment by srafiqa** [comment]
I am getting the same issue on real devices randomly and is really bugging me . It would be great if anyone could resolve this issue?
I have to do the below work around to get working sometimes and sometimes the work around also of no use.
workaround 1 - run the below command in the affected device
`adb uninstall io.appium.uiautomator2.server`
`adb uninstall io.appium.uiautomator2.server.test`
workaround 2 :  factory reset of the device
I haven't got any reply when i posted this issue . Link is provided below for the reference and the details of the issue.

https://discuss.appium.io/t/uiautomator2-server-3-1-1-instrumentation-result-shortmsg-process-crashed-the-instrumentation-process-has-been-unexpectedly-terminated/25483/3

**Comment by wswebcreation** [comment]
I'm going to close this issue. All the startup issues are related to Appium and not to WebdriverIO. Please file an issue on the Appium github page instead of here
