### ISSUE TITLE
Doesn't work after following all setup steps and calling the same run command.

### ISSUE THREAD

**Issue by PHUITesting** [webdriverio/appium-boilerplate#23]
Am I missing something?

Test Suites:     0 passed, 6 failed, 6 total (100% completed)
Time:            🕛  6.75s

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-boilerplate@5.2.0 android.app: `wdio ./config/wdio.android.app.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-boilerplate@5.2.0 android.app script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by wswebcreation** [comment]
Hi

Thanks for filling an issue. Can you provide more info, like the additional log (post it as a file instead of pasting it here).

Can you also explain which tests you followed, what operating system you use and so on?

Tnx

**Comment by wswebcreation** [comment]
Going to close this one due to inactivity
