### ISSUE TITLE
How can I include the printscreen on error either on web/mobile?

### ISSUE THREAD

**Issue by xyngfei** [webdriverio/appium-boilerplate#24]
**Describe your question with as much detail as possible**
As mentioned by title.

I did use the following code on wdio.conf.js, however, it doesn't work.

> afterTest: function (test) {
>         // if (test.error !== undefined && driver !== undefined) {
>         driver.takeScreenshot();
>         // driver.saveScreenshot('assertionError_' + assertion.error.message + '.png');
>         // }
>     }

**Comment by wswebcreation** [comment]
@xyngfei 

Please ask these type of questions on the Gitter channel of WebdriverIO. This is where this issue option on GitHub is for and it's also not related to this boilerplate
