### ISSUE TITLE
Unable to start appium server while using webdriverio v4.

### ISSUE THREAD

**Issue by Zarmeena** [webdriverio/appium-boilerplate#25]
**Environment :**
- Node version: 12.2.0
 - Platform:  Android
 - Platform version: 8.0.0
 - Emulator/Simulator/Real Device: Emulator

**Describe the bug**
While executing 'npm run android.app' command, I am getting the following error:

**9 verbose lifecycle appium-boilerplate@0.1.0~android.app: CWD: /Users/saurabhdubey/Downloads/appium-boilerplate-4
10 silly lifecycle appium-boilerplate@0.1.0~android.app: Args: [ '-c', 'wdio ./config/wdio.android.app.conf.js' ]
11 silly lifecycle appium-boilerplate@0.1.0~android.app: Returned: code: 1  signal: null
12 info lifecycle appium-boilerplate@0.1.0~android.app: Failed to exec android.app script
13 verbose stack Error: appium-boilerplate@0.1.0 android.app: `wdio ./config/wdio.android.app.conf.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:159:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:159:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid appium-boilerplate@0.1.0
15 verbose cwd /Users/saurabhdubey/Downloads/appium-boilerplate-4
16 verbose Darwin 18.5.0
17 verbose argv "/usr/local/Cellar/node/9.3.0_1/bin/node" "/usr/local/bin/npm" "run" "android.app"
18 verbose node v9.3.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error appium-boilerplate@0.1.0 android.app: `wdio ./config/wdio.android.app.conf.js`
22 error Exit status 1
23 error Failed at the appium-boilerplate@0.1.0 android.app script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]**

**Expected behavior**
On invoking this command from terminal, the appium service should start and test cases should start executing. It is working fine in v5 of the same project.

**Comment by wswebcreation** [comment]
@Zarmeena 

Does this also happen for iOS or only for Android. Can you also check the npm logs and see what errors are thrown?

**Comment by Zarmeena** [comment]
[2019-05-16T04_23_47_637Z-debug.log](https://github.com/webdriverio/appium-boilerplate/files/3185392/2019-05-16T04_23_47_637Z-debug.log)

[wdio.android.app.conf.txt](https://github.com/webdriverio/appium-boilerplate/files/3185399/wdio.android.app.conf.txt)

We have tested it on Android emulator only. Have attached the npm log and 'wdio.android.app.conf.js' file for your reference. Please let me know if you need any additional details.

**Comment by wswebcreation** [comment]
@Zarmeena 

I've done a clean checkout on my machine (Mac with Node `v10.15.2` and NPM `6.9.0` and it's just running. To be honest, I've never seen this error that you are showing for V4.
Secondly support for V4 has stopped. I'm going to close this issue now because of this.
