### ISSUE TITLE
circleci

### ISSUE THREAD

**Issue by johnhiggs** [webdriverio/appium-boilerplate#29]
**Is your feature request related to a problem?**
Havent been able to successfully set up to run in circleci, have tried so many different things

**Describe the solution you'd like**
A working sample of a config.yml that works alongside the appium wdio sync service and the macos executor

**Additional context**
I may be able to get it to work just using docker container but it will add much more time

Ive also opened up a support ticket with circleci and commented on an announcement they had recently... related:
* https://discuss.circleci.com/t/xcode-11-beta-3-image-released/31374

* https://discuss.circleci.com/t/java-version-does-not-work-using-macos-xcode/31660

I think that is what my problem is and the tests time out.

Here is my sample config.yml (i’ve renamed app to XXXApp for privacy)

```version: 2.1

# Short-hand
defaults: &defaults
    macos:
        xcode: "11.0.0"
    working_directory: ~/react-native

# Jobs
jobs:
    build-test:
        <<: *defaults
        steps:

            - run: ls -R /Library/Java/
            - run:
                name: this is the jvm of the container
                command: /usr/libexec/java_home
            - run: echo $JAVA_HOME
            - run: echo $PATH
            - run:
                name: js > java
                command: |
                    echo 'export JAVA_HOME=$(/usr/libexec/java_home)' >> $BASH_ENV
                    echo 'export PATH=${JAVA_HOME}/bin:$PATH' >> $BASH_ENV
                    source $BASH_ENV
            - run: yarn global add appium-doctor
            - run: appium-doctor
            - checkout
            - attach_workspace:
                at: ~/react-native
            - restore_cache:
                name: Restore Yarn Package Cache
                keys:
                    - yarn-packages-{{ checksum "yarn.lock" }}
            - run:
                name: Install Dependencies
                command: yarn
            - run:
                name: Install Carthage
                command: |
                    brew update
                    brew install carthage
            - save_cache:
                name: Save Yarn Package Cache
                key: yarn-packages-{{ checksum "yarn.lock" }}
                paths:
                    - ~/.cache/yarn
            - run:
                name: Install Cocoa Pods
                command: pod install
                working_directory: ios
            - run:
                name: Xcodebuild workspace with specified derived data directory
                command: xcodebuild -workspace ios/XXXApp.xcworkspace -scheme XXXApp -UseModernBuildSystem=NO -configuration Debug -sdk iphonesimulator -derivedDataPath derivedData
            - run:
                name: e2e smoke tests
                command: yarn e2e-circleciTests:ios

# Workflows
workflows:
    version: 2
    e2e_smokeTests:
        jobs:
            - build-test

**Comment by christian-bromann** [comment]
Can you please provide a proper description of the issue?

**Comment by wswebcreation** [comment]
Thanks for your question here, but this is in my opinion not related to this specific boiler plate mainly because we don't support circleci with this boilerplate. We only want to help people giving them a quick start with WebdriverIO and Appium.

My suggestion would be to check or the guiter channel or check the Appium discussion groups.

For now ai'm going to close this

**Comment by johnhiggs** [comment]
@wswebcreation  do you support or have used similar with any CI tool?
