### ISSUE TITLE
Error: spawn appium ENOENT     at Process.ChildProcess._handle.onexit

### ISSUE THREAD

**Issue by navaneetit09** [webdriverio/appium-boilerplate#32]
**Describe your question with as much detail as possible**
A clear and concise question that doesn't require too much conversation. Need more help? [Find me on Gitter](https://gitter.im/wswebcreation)

**If it's about a specific piece of code, try and include some of it to support your question.**
[...]
 node --version
v10.15.3

NPM --version
6.9.0
appium --version
1.14.2

WebdriverIO: 5.12.4
Platform: [Android]

Real Device.

Cloned project from boilerplate and copied .apk file in .apps directory and when running 
npm run android.app
getting below errors..

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn appium ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-boilerplate@5.3.1 android.app: `wdio ./config/wdio.android.app.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-boilerplate@5.3.1 android.app script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output abov

**Comment by wswebcreation** [comment]
@navaneetit09 

Did you prep your environment properly with Appium and Android?  Can you start an appium session from the command line?

**Comment by navaneetit09** [comment]
Yes, i prepared appium and env with "npm install"

And i am able to start appium from command line.

appium
[Appium] Welcome to Appium v1.14.2
[Appium] Appium REST http interface listener started on 0.0.0.0:4723

**Comment by navaneetit09** [comment]
Below are the steps i followed to run appium-boilerplate:

Downloaded appium-boilerplate-master on my local and unzipped it.
Now i opened unzipped appium-boilerplate-master in VSCode.
Also downloaded Android-NativeDemoApp-0.2.1.apk from given link and created one .apps directory and copied there.

Now i ran "npm install"
Then i ran "npm run android.app"

while running above command i am getting below error.

> appium-boilerplate@5.3.1 android.app C:\Users\navkumar13\Desktop\appium-boilerplate-master
> wdio ./config/wdio.android.app.conf.js


Execution of 6 spec files started at 2019-10-31T05:22:01.017Z

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn appium ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by wswebcreation** [comment]
Can you share the logs by running the command again with a debug option enabled, so please run `npm run android.app -- --logLevel=debug` and post the logs here?

**Comment by navaneetit09** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\navkumar13\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'android.app',
1 verbose cli   '--',
1 verbose cli   '--logLevel=debug' ]
2 info using npm@6.9.0
3 info using node@v10.15.3
4 verbose run-script [ 'preandroid.app', 'android.app', 'postandroid.app' ]
5 info lifecycle appium-boilerplate@5.3.1~preandroid.app: appium-boilerplate@5.3.1
6 info lifecycle appium-boilerplate@5.3.1~android.app: appium-boilerplate@5.3.1
7 verbose lifecycle appium-boilerplate@5.3.1~android.app: unsafe-perm in lifecycle true
8 verbose lifecycle appium-boilerplate@5.3.1~android.app: PATH: C:\Users\navkumar13\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\navkumar13\Desktop\appium-boilerplate-master\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;"C:\Program Files (x86)\Common Files\Oracle\Java\javapath;";C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Box\Box Edit\;"C:\Users\navkumar13\AppData\Local\Programs\Python\Python37-32;";C:\Users\navkumar13\AppData\Local\Programs\Python\Python37-32\Scripts;C:\Program Files\PuTTY\;C:\Users\navkumar13\AppData\Local\Programs\Python\Python37-32\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\Java\jdk1.8.0_211\bin;C:\Users\navkumar13\AppData\Local\Android\Sdk\tools;C:\Users\navkumar13\AppData\Local\Android\Sdk\tools\bin;C:\Users\navkumar13\AppData\Local\Android\Sdk\platform-tools;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\navkumar13\.windows-build-tools\python27\;C:\Users\navkumar13\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\navkumar13\AppData\Roaming\npm\node_modules\windows-build-tools\node_modules\.bin;C:\Users\navkumar13\AppData\Roaming\npm\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;"C:\Program Files (x86)\Common Files\Oracle\Java\javapath;";C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Box\Box Edit\;"C:\Users\navkumar13\AppData\Local\Programs\Python\Python37-32;";C:\Users\navkumar13\AppData\Local\Programs\Python\Python37-32\Scripts;C:\Program Files\PuTTY\;C:\Users\navkumar13\AppData\Local\Programs\Python\Python37-32\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\navkumar13\AppData\Local\Microsoft\WindowsApps;C:\Users\navkumar13\AppData\Roaming\npm;C:\Users\navkumar13\AppData\Local\Programs\Microsoft VS Code\bin
9 verbose lifecycle appium-boilerplate@5.3.1~android.app: CWD: C:\Users\navkumar13\Desktop\appium-boilerplate-master
10 silly lifecycle appium-boilerplate@5.3.1~android.app: Args: [ '/d /s /c',
10 silly lifecycle   'wdio ./config/wdio.android.app.conf.js "--logLevel=debug"' ]
11 silly lifecycle appium-boilerplate@5.3.1~android.app: Returned: code: 1  signal: null
12 info lifecycle appium-boilerplate@5.3.1~android.app: Failed to exec android.app script
13 verbose stack Error: appium-boilerplate@5.3.1 android.app: `wdio ./config/wdio.android.app.conf.js "--logLevel=debug"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\navkumar13\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\navkumar13\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid appium-boilerplate@5.3.1
15 verbose cwd C:\Users\navkumar13\Desktop\appium-boilerplate-master
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\navkumar13\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "android.app" "--" "--logLevel=debug"
18 verbose node v10.15.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error appium-boilerplate@5.3.1 android.app: `wdio ./config/wdio.android.app.conf.js "--logLevel=debug"`
22 error Exit status 1
23 error Failed at the appium-boilerplate@5.3.1 android.app script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by navaneetit09** [comment]
Could you please have a look on logs and suggest me what should i do next.

**Comment by lefoy** [comment]
I'm having the same issue with iOS, cloned the project, added the .ipa in the apps folder, ran `npm install` then `npm run ios.app` and I have the same error (`events.js:174 throw er; // Unhandled 'error' event`)

**Comment by navaneetit09** [comment]
Is it supported for reactive native code also?

**Comment by lefoy** [comment]
I got it working by updating all my wdio packages. Here are the versions I'm currently using:
```
"@wdio/appium-service": "^5.13.2",
"@wdio/cli": "^5.15.6",
"@wdio/jasmine-framework": "^5.15.1",
"@wdio/local-runner": "^5.15.6",
"@wdio/sauce-service": "^5.14.0",
"@wdio/spec-reporter": "^5.15.2",
"@wdio/sync": "^5.15.7",
```

**Comment by wswebcreation** [comment]
Is this issue still valid, also after updating to all the latest versions of the dependencies? I haven't had problems with it on my local machine and if not I'm going to close it.

**Comment by navaneetit09** [comment]
Hi,
Thanks for your reply. Updating solved the issue.

**Comment by wswebcreation** [comment]
Thanks for updating and closing

**Comment by dalu547** [comment]
I did all the above but still iam getting same issue as like below,

events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn appium ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn appium',
  path: 'appium',
  spawnargs: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-boilerplate@5.3.1 android.app: `wdio ./config/wdio.android.app.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-boilerplate@5.3.1 android.app script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dalayya.kalla\AppData\Roaming\npm-cache\_logs\2019-12-23T19_12_58_715Z-debug.log

Help me inthis.

**Comment by wswebcreation** [comment]
@dalu547 

Can you run the test again with `logLevel=debug` and post the logs of WebdriverIO here in proper Markdown?
I now got a proper Windows machine so I can check it. Tnx

**Comment by dalu547** [comment]
Below is my log file,

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'android.app',
1 verbose cli   '--',
1 verbose cli   '--logLevel=debug'
1 verbose cli ]
2 info using npm@6.12.0
3 info using node@v12.13.0
4 verbose run-script [ 'preandroid.app', 'android.app', 'postandroid.app' ]
5 info lifecycle appium-boilerplate@5.3.1~preandroid.app: appium-boilerplate@5.3.1
6 info lifecycle appium-boilerplate@5.3.1~android.app: appium-boilerplate@5.3.1
7 verbose lifecycle appium-boilerplate@5.3.1~android.app: unsafe-perm in lifecycle true
8 verbose lifecycle appium-boilerplate@5.3.1~android.app: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\WebdriverIO\appium-boilerplate\node_modules\.bin;C:\Program Files\Java\jre1.8.0_172\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\Users\dalayya.kalla\AppData\Local\Microsoft\WindowsApps;C:\tizen-studio\platforms\tizen-5.0\common\tidl;C:\Program Files\Java\jdk1.8.0_172\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Program Files\Microsoft VS Code\bin;C:\Users\dalayya.kalla\AppData\Local\Android\Sdk\tools;C:\Users\dalayya.kalla\AppData\Local\Android\Sdk\platform-tools;C:\Gradle\gradle-4.1-bin\gradle-4.1\bin;C:\Program Files\nodejs;C:\Windows\System32;C:\tizen-studio\tools\ide\bin;C:\Users\dalayya.kalla\AppData\Local\Microsoft\WindowsApps;;C:\Users\dalayya.kalla\AppData\Local\Microsoft\WindowsApps;C:\Users\dalayya.kalla\AppData\Roaming\npm
9 verbose lifecycle appium-boilerplate@5.3.1~android.app: CWD: D:\WebdriverIO\appium-boilerplate
10 silly lifecycle appium-boilerplate@5.3.1~android.app: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'wdio ./config/wdio.android.app.conf.js "--logLevel=debug"'
10 silly lifecycle ]
11 silly lifecycle appium-boilerplate@5.3.1~android.app: Returned: code: 1  signal: null
12 info lifecycle appium-boilerplate@5.3.1~android.app: Failed to exec android.app script
13 verbose stack Error: appium-boilerplate@5.3.1 android.app: `wdio ./config/wdio.android.app.conf.js "--logLevel=debug"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid appium-boilerplate@5.3.1
15 verbose cwd D:\WebdriverIO\appium-boilerplate
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "android.app" "--" "--logLevel=debug"
18 verbose node v12.13.0
19 verbose npm  v6.12.0
20 error code ELIFECYCLE
21 error errno 1
22 error appium-boilerplate@5.3.1 android.app: `wdio ./config/wdio.android.app.conf.js "--logLevel=debug"`
22 error Exit status 1
23 error Failed at the appium-boilerplate@5.3.1 android.app script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by wswebcreation** [comment]
Hmm,

When I look at this I can't really find the problem in your logs, when I run it on my Windows machine I get this

```log
$ ./node_modules/.bin/wdio ./config/wdio.android.app.conf.js --logLevel=debug

Execution of 6 spec files started at 2019-12-24T08:52:17.196Z

2019-12-24T08:52:17.201Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "appium"
2019-12-24T08:52:17.317Z INFO @wdio/cli:launcher: Run onPrepare hook
2019-12-24T08:52:17.318Z DEBUG @wdio/appium-service: Will spawn Appium process: appium
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: spawn appium ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:19)
    at onErrorNT (internal/child_process.js:431:16)
    at processTicksAndRejections (internal/process/task_queues.js:83:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:58:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:828:11)
    at internal/main/run_main_module.js:17:11
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
    at onErrorNT (internal/child_process.js:431:16)
    [... lines matching original stack trace ...]
    at internal/main/run_main_module.js:17:11
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

with `yarn` or `npm`. This looks like an issue in the `@wdio/appium-service`. I'll file a ticket there and link it here

**Comment by wswebcreation** [comment]
https://github.com/webdriverio/webdriverio/issues/4914

**Comment by dalu547** [comment]
Hi @wswebcreation ,

Fixed and working as expected. I did below changes,

Commented below lines in
 **_startAppium(command, args, waitStartTime, callback) {
}**

// let process = (0, _child_process.spawn)(command, args, {
    //   stdio: ['ignore', 'pipe', 'pipe']
    // });

And added below line instead of commented lines.
    let process = spawn(command, args, { stdio: ['ignore', 'pipe', 'pipe'] })

Method location: 
_node_modules/@wdio/appium-service/build/launcher.js_ 

Thanks.

**Comment by wswebcreation** [comment]
@dalu547 

I new version of the appium-service will be released soon which holds this fix

**Comment by AbdulMuqeetalam** [comment]
I am facing a issue in building a react native app. When I scan the QR code from my mobile expo app this error occurs.

info Launching Dev Tools...
Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:485:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by SurajTopal** [comment]
@AbdulMuqeetalam how do you resolve your error ? 

> I am facing a issue in building a react native app. When I scan the QR code from my mobile expo app this error occurs.
> 
> info Launching Dev Tools... Error: spawn cmd ENOENT at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19) at onErrorNT (node:internal/child_process:485:16) at processTicksAndRejections (node:internal/process/task_queues:83:21)

same issue i am facing
