### ISSUE TITLE
the spec/exclude command doesn't work to test on a single file

### ISSUE THREAD

**Issue by bluemoon711** [webdriverio/appium-boilerplate#34]
**Describe your question with as much detail as possible**
A clear and concise question that doesn't require too much conversation. Need more help? [Find me on Gitter](https://gitter.im/wswebcreation)
Hi there, 
I repo the appium-biolerplate and installed as the ReadMe suggested. My question is how I could run a single test not multiple tests. I tried to add "--spec"/"--exclude" [file name] to filter the test I want to test, but either of them worked.

**If it's about a specific piece of code, try and include some of it to support your question.**
[$npm run ios.browser  //it will test 4 files.
I tried to run `npm run ios.browser --spec browser.checkbox.spec.js` , but it still will run 4 files to test. I also tried to run `npm run ios.browser --exclude browser.checkbox.spec.js`, and it will run 4 files to test as well.
]

**Environment (please complete the following information):**
 - Node.js version: 12.4.0
 - NPM version: [e.g. 5.8.0]
 - Platform: iOS
 - Platform version: 11.3,
 - Emulator/Simulator/Real Device: iPhone X

**Additional context**

**Comment by christian-bromann** [comment]
If you run it via the NPM command, you need to do:

```sh
$ npm run ios.browser -- --spec browser.checkbox.spec.js
```

Cheers!
