### ISSUE TITLE
Add description on how to setup from zero

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/appium-boilerplate#5]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/native-demo-app) and submit a pull request

**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [ ] Other

**Description of the improvement / report**

For someone who is new to mobile testing it would be definitely helpful to find a get started documentation on where to download xCode or Android and how to download and setup a specific iOS/Android version. This doesn't need to be a comprehensive tutorial. A step by step list with links to helpful "Getting Started" docs from other sources should be sufficient.

I just realised this when trying to start the test and have seen that I don't have the expected iOS version installed as defined in the wdio.conf.

**Comment by wswebcreation** [comment]
Tnx, will update that
