### ISSUE TITLE
This project has Type compile issue  'Type 'ChainablePromiseElement' is not assignable to type 'Element'.'

### ISSUE THREAD

**Issue by rajivnw** [webdriverio/appium-boilerplate#523]
**Environment (please complete the following information):**
 - Node.js version: 20

**Describe the bug**
when checkout this project I noticed Type compile issue  'Type 'ChainablePromiseElement' is not assignable to type 'Element'.'

**To Reproduce**
take a checkout and do npm install and check in LoginScreen.ts
<img width="805" alt="image" src="https://github.com/user-attachments/assets/01ec4b8e-3d8f-4c17-906a-f133d5d51256">

**Additional context**
seems below method signature for element has changed now its returning ChainablePromiseElement.
function $(selector: Selector): ChainablePromiseElement

Is there way to fix this as for existing projects its a bigger change. All the method signatures, if they are accepting WebDriverIO.Element as param, have to update.

**Comment by wswebcreation** [comment]
Hi @rajivnw 

Thanks for logging the issue, can you please log it [here](https://github.com/webdriverio/webdriverio/issues/new?assignees=&labels=Bug+%F0%9F%90%9B%2CNeeds+Triaging+%E2%8F%B3&projects=&template=bug_report.yml&title=%5B%F0%9F%90%9B+Bug%5D%3A+%3Ctitle%3E) so it will get the correct attention?
