### ISSUE TITLE
Unable to run the project

### ISSUE THREAD

**Issue by dipti-code** [webdriverio/appium-boilerplate#66]
**Describe your question with as much detail as possible**
A clear and concise question that doesn't require too much conversation. Need more help? [Find me on Gitter](https://gitter.im/wswebcreation)

I downloaded the repo and the project, did npm install.

But unable to run the project,
Do i have to stick to webdriverIO version 5 , because i updated to version 6.

**If it's about a specific piece of code, try and include some of it to support your question.**
[...]

**Environment (please complete the following information):**
 - Node.js version: [e.g. 8.9.1]
 - NPM version: [e.g. 5.8.0]
 - Platform: [e.g. Android]
 - Platform version: [e.g. 8.1.0]
 - Emulator/Simulator/Real Device: [e.g. Emulator]

**Additional context**

**Comment by wswebcreation** [comment]
@dipti-code 

Can you be a bit more clear about this? Are you on 6 currently? If so, I'm busy with updating it to V6 but I'm experiencing some issues with Appium

**Comment by dipti-code** [comment]
Yes am in webdriverIO version 6 .

my package.json is like this ,

 "devDependencies": {
    "@babel/cli": "^7.7.7",
    "@babel/core": "^7.7.7",
    "@babel/preset-env": "^7.7.7",
    "@babel/register": "^7.7.7",
    "@babel/traverse": "^7.7.4",
    "@babel/types": "^7.7.4",
    "@wdio/appium-service": "^6.0.12",
    "@wdio/cli": "^6.0.13",
    "@wdio/jasmine-framework": "^6.0.12",
    "@wdio/local-runner": "^6.0.13",
    "@wdio/sauce-service": "^6.0.13",
    "@wdio/spec-reporter": "^6.0.12",
    "@wdio/sync": "^6.0.12",
    "babel-eslint": "^10.0.3",
    "eslint": "^6.8.0",
    "eslint-config-standard": "^14.1.0",
    "eslint-plugin-import": "^2.19.1",
    "eslint-plugin-node": "^10.0.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.1",
    "eslint-plugin-wdio": "^5.13.2",
    "node-fetch": "^2.6.0",
    "webdriverio": "^6.0.13"
  }
}

Could you please make me clear, if i want to run my app, with some modification in the code, will it run on version 5 or version 6.

and you said you are busy with updating v6, how it could hamper to run the project?

**Comment by wswebcreation** [comment]
This boilerplate is now setup for working with V5. You need to wait a few days untill I have time to fix all things for V6

**Comment by dipti-code** [comment]
Thanks @wswebcreation . But could you please guide me if i setup my own project from scratch with v6, then what are the ares to be need to take care of.
i am totally new to webdriveriO, so my questions may seems very childish.

**Comment by wswebcreation** [comment]
@dipti-code 

I've updated the project to V6, so if you take a look again it should work now
