### ISSUE TITLE
Unable to install the app 

### ISSUE THREAD

**Issue by dipti-code** [webdriverio/appium-boilerplate#67]
**Environment (please complete the following information):**
 - Node.js version: [e.g. 8.9.1] 
 - NPM version: [e.g. 5.8.0]
 - Platform: [e.g. Android] iOS real device
 - Platform version: [e.g. 8.1.0] 13.3.1
 - Emulator/Simulator/Real Device: [e.g. Emulator] Real Device
<img width="426" alt="Screenshot 2020-04-07 at 6 11 01 PM" src="https://user-images.githubusercontent.com/63293480/78671904-8912ef80-78fd-11ea-968c-3db5c781bae0.png">

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by wswebcreation** [comment]
You can't install the app on a real device of your own because the app needs to be signed with a licence that includes your device id
