### ISSUE TITLE
Getting "Cannot use import statement outside a module" when running sample code

### ISSUE THREAD

**Issue by peterpham** [webdriverio/appium-boilerplate#72]
**Environment (please complete the following information):**
 - Node.js version: 13.12.0
 - NPM version: 6.13.4
 - Platform: Chrome
 - Platform version: 80.0
 - Emulator/Simulator/Real Device: 

**Describe the bug**
Getting error "Cannot use import statement outside a module" when running sample code under /examples/pageobject
```
> @ test /Users/phampp/Downloads/webdriverio/examples/pageobject
> ../../packages/wdio-cli/bin/wdio.js ./wdio.conf.js


Execution of 1 spec files started at 2020-04-14T07:55:43.791Z

[0-0] RUNNING in chrome - /specs/dynamic.spec.js
[0-0]  Error:  Failed to create session.
Unexpected token < in JSON at position 0 in "http://localhost:4444/session"
[0-0] FAILED in chrome - /specs/dynamic.spec.js

Spec Files:	 0 passed, 1 failed, 1 total (100% completed) in 00:00:02 

npm ERR! Test failed.  See above for more details.
```

**To Reproduce**
```
git clone git@github.com:webdriverio/webdriverio.git
cd ./webdriverio
npm install
npm run setup
cd examples/pageobject/
npm test
```
After this, it failed with the above error

**Expected behavior**
Tests should run successfully

**Comment by wswebcreation** [comment]
Hi @peterpham 

This is not related to the `appium-boilerplate`, but with WebdriverIO, please file the issue  there
