### ISSUE TITLE
Switch App to browser and back to app both in android and iOS

### ISSUE THREAD

**Issue by dipti-code** [webdriverio/appium-boilerplate#73]
**Is your feature request related to a problem? Please describe.**
_### I have my hybrid app running working fine. but when i click login button, it opens another windows for iDP login in browser. and i need to eneter the value over there and also back again to the app.
*_*Describe the solution you'd like**
_A clear and concise description of what you want to happen.
i have a situation where , my app opens a webpage different from my app(browsers), how to handle those elements in that webpage and then back to the original app after login as its a idp page._
**Describe alternatives you've considered**
<img width="965" alt="Screenshot 2020-04-16 at 12 20 06 PM" src="https://user-images.githubusercontent.com/63293480/79436651-c7d83200-7fee-11ea-8feb-23e21c7a39ea.png">

**Additional context**

**Comment by wswebcreation** [comment]
Hi @dipti-code 

This channel is not really for getting support, so going to close this issue for now. I do have some articles for you that might help

- https://saucelabs.com/blog/how-to-automate-a-real-e2e-user-flow-with-appium-for-android-devices
- https://saucelabs.com/blog/how-to-automate-a-real-e2e-user-flow-with-appium-for-iOS-devices

**Comment by dipti-code** [comment]
@wswebcreation Thanks very much. The guide helps me to work in Android.
But in iOS its giving 
Error: waitUntil condition failed with the following reason: Cannot read property 'includes' of undefined

**Comment by ExploreTech01** [comment]
@wswebcreation In my case I am able to link in mobile chrome browser using below command
**androidDriver.startActivity(new Activity("com.android.chrome", "com.google.android.apps.chrome.Main")); // chrome**
But I am able to perform any action on chrome browser.

Please help...!

**Comment by ExploreTech09** [comment]
@wswebcreation In my case I am able to redirect to mobile chrome browser using below command
**androidDriver.startActivity(new Activity("com.android.chrome","com.google.android.apps.chrome.Main"));**
However not action is performing on chrome browser.

**Comment by wswebcreation** [comment]
Hi @ExploreTech09 

What action would you expect would happen when you call 

`androidDriver.startActivity(new Activity("com.android.chrome","com.google.android.apps.chrome.Main")`

**Comment by ExploreTech09** [comment]
Hi @wswebcreation,
Thanks, The issue which i was facing is resolved.
