### ISSUE TITLE
in iOS its showing Some specific webview_xxxx

### ISSUE THREAD

**Issue by dipti-code** [webdriverio/appium-boilerplate#74]
After writing the code 
 driver.waitUntil(() => {
            // Get all the contexts, that could look like this
            const contexts = driver.getContexts();
            // Log them to the console
            console.log('contexts = ', contexts);
        
            // Just return false so this function will never return a truthy value
            return false;
        }, 15000);

The out puts are always 

[0-0] contexts =  [
  'NATIVE_APP',
  'WEBVIEW_10504.11',
  'WEBVIEW_25791.1',
  'WEBVIEW_25791.2'
]
[0-0] contexts =  [
  'NATIVE_APP',
  'WEBVIEW_10504.11',
  'WEBVIEW_25791.1',
  'WEBVIEW_25791.2'
]
[0-0] contexts =  [
  'NATIVE_APP',
  'WEBVIEW_10504.11',
  'WEBVIEW_25791.1',
  'WEBVIEW_25791.2'
]
[0-0] contexts =  [
  'NATIVE_APP',
  'WEBVIEW_10504.11',
  'WEBVIEW_25791.1',
  'WEBVIEW_25791.2'
]

Then how to track what browsers its opening

my config has 'appium:includeSafariInWebviews': 'true',

**Comment by dipti-code** [comment]
and the config has 'appium:fullContextList': 'true', is added its started showing error 
Error: Malformed type for "name" parameter of command switchContext
Expected: string
Actual: object

**Comment by wswebcreation** [comment]
@dipti-code 

Going to close this. Like I said, this is not the channel to ask questions

**Comment by dipti-code** [comment]
> @dipti-code
> 
> Going to close this. Like I said, this is not the channel to ask questions

@wswebcreation  Sorry , forgot totally. Please.
