### ISSUE TITLE
setValue function for Android DropDown is throwing error

### ISSUE THREAD

**Issue by jayshreekant** [webdriverio/appium-boilerplate#76]
I am getting the error in setvalue method for Android Dropdown.

v5

Error: element ("//android.widget.ListView") still not existing after 10000ms

**Comment by christian-bromann** [comment]
As you can see your dropdown element does not exist. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by jayshreekant** [comment]
But no one replies in that channel, so I opened this issue

**Comment by jayshreekant** [comment]
Can you suggest how to overcome it?
