### ISSUE TITLE
How to verify IOS Picker wheel values [Drop Down Values]

### ISSUE THREAD

**Issue by jayshreekant** [webdriverio/appium-boilerplate#77]
Can some one help me in verfying IOS Picker wheel values [Drop Down Values]

**Comment by wswebcreation** [comment]
Please ask these questions on the Gitter Channel of WebdriverIO

**Comment by jayshreekant** [comment]
Dear wim, no one bother to reply there, I am stuck badly 
There is no proper documentation, How we will promote ?
