### ISSUE TITLE
The URL '/session' did not map to a valid resource

### ISSUE THREAD

**Issue by natkrish** [webdriverio/appium-boilerplate#81]
**Environment:**
 - Node.js version: 12.16.1
 - NPM version: 6.14.4 
 - Platform:Android
 - Platform version: 9.0 and  10.0 
 - Emulator/Simulator/Real Device: Emulator & Real Device

**Describe the bug**
When running the boilerplate project for android browser or the android app - I get an error 

**To Reproduce**
Nothing i think its environmental but dont know how to fix it.  May be worth replicating the environment 

**Expected behavior**
I should be able to run both browser test and app test 

**Screenshots**
![image](https://user-images.githubusercontent.com/12541984/94740549-c9ae6b80-036a-11eb-8ef7-7ee3e4c46b82.png)

![image](https://user-images.githubusercontent.com/12541984/94740607-ddf26880-036a-11eb-9bbf-e62600bf3df7.png)

**Additional context**

**Comment by wswebcreation** [comment]
Hi @natkrish 

Can you provide more information about what you are doing? Is it an emulator that you are connecting to or a real device? Based on the info it looks that there is not device connected that matches your provided capabilities

**Comment by wswebcreation** [comment]
Going to close this one due to inactivity. Feel free to re-open it again if needed and please provide the needed info

**Comment by cakekindel** [comment]
Hi @wswebcreation I'm running into this myself, I'm running Appium Desktop v1.18.3, `appium-doctor` in the same shell says everything is okilly dokilly.

The server is running, and logs this when trying to execute `npm run android.app`:
<details>
  <summary>
 Appium server logs - npm run android.app (click to expand)
</summary>
  
```
[HTTP] --> POST /session
[HTTP] {"capabilities":{"alwaysMatch":{"platformName":"Android","appium:deviceName":"Pixel_3_API_29","appium:platformVersion":"10.0","appium:orientation":"PORTRAIT","appium:automationName":"UiAutomator2","appium:app":"/home/orion/src/strongmind/app/appium-boilerplate/apps/Android-NativeDemoApp-0.2.1.apk","appium:noReset":true,"appium:newCommandTimeout":240},"firstMatch":[{}]},"desiredCapabilities":{"platformName":"Android","appium:deviceName":"Pixel_3_API_29","appium:platformVersion":"10.0","appium:orientation":"PORTRAIT","appium:automationName":"UiAutomator2","appium:app":"/home/orion/src/strongmind/app/appium-boilerplate/apps/Android-NativeDemoApp-0.2.1.apk","appium:noReset":true,"appium:newCommandTimeout":240}}
[debug] [HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- POST /session 404 1 ms - 50
```

</details>

I can successfully start a session in the Appium Inspector with the same capabilities, here are the logs when I do so:

<details>
  <summary>
 Appium server logs - Start session with Inspector (click to expand)
  </summary>
  
```
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"deviceName":"Pixel_3_API-29","ensureWebviewsHavePages":true,"platformName":"Android","platformVersion":"10.0","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"deviceName":"Pixel_3_API-29","ensureWebviewsHavePages":true,"platformName":"Android","platformVersion":"10.0","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1604703260189 (15:54:20 GMT-0700 (Mountain Standard Time))
[Appium]
[Appium] ======================================================================
[Appium]   DEPRECATION WARNING:
[Appium]
[Appium]   The 'automationName' capability was not provided in the desired
[Appium]   capabilities for this Android session
<snip> (I was lazy and didn't specify UiAutomator :P)
[Appium] ======================================================================
[Appium]
[Appium] Appium v1.18.3 creating new AndroidUiautomator2Driver (v1.56.1) session
[Appium] Applying relaxed security to 'AndroidUiautomator2Driver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure

<snip> (DEBUG logs for the successfully started session)

[HTTP] <-- POST /wd/hub/session 200 9223 ms - 881
```

</details>

Notably, the appium wdio service is making POST requests to `/session`, inspector is POSTing to `/wd/hub/session` - is this repo out of date with the appium server? or is the wdio service config expecting an older version of appium desktop?

Thanks :smile:

**Comment by wswebcreation** [comment]
Hi @cakekindel 

> Notably, the appium wdio service is making POST requests to /session, inspector is POSTing to /wd/hub/session - is this repo out of date with the appium server?

No, `wd/hub` is officially not needed anymore, the default path is just `/`.

I just ran the boilerplate again on my machine and it's still working, even without the latest WDIO packages. What happens if you start the appium server separately with `appium --base-path /` and then run it? Can you then past the logs of the appium server into here?

**Comment by lasselaakkonen** [comment]
> start the appium server separately with `appium --base-path /`

@cakekindel That fixed the issue for me.

I am using latest commit from master https://github.com/webdriverio/appium-boilerplate/commit/1a8041a1d6269f74ffb6e10bb48ed17761a1e7f5 and `appium@1.18.3`.

Without `--base-path /` config WDIO says:

```
[0-0] RUNNING in Android - /tests/specs/app.login.spec.js
[0-0]  Error:  Failed to create session.
The URL '/session' did not map to a valid resource
```

And appium says:

```
[Appium] Welcome to Appium v1.18.3
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /session
[HTTP] {"capabilities":{"alwaysMatch":{"platformName":"Android","appium:automationName":"UiAutomator2","appium:app":"....debug.apk","appium:noReset":true,"appium:newCommandTimeout":240},"firstMatch":[{}]},"desiredCapabilities":{"platformName":"Android","appium:automationName":"UiAutomator2","appium:app":"....debug.apk","appium:noReset":true,"appium:newCommandTimeout":240}}
[debug] [HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- POST /session 404 11 ms - 50
```

**Comment by dancomanlive** [comment]
```
npm run ios.app

> appium-boilerplate@5.3.1 ios.app /Users/dancoman/Downloads/Workspace/webdriverIOAppium/appium-boilerplate
> wdio ./config/wdio.ios.app.conf.js


Execution of 6 spec files started at 2020-11-30T20:44:21.420Z

[0-0] RUNNING in iOS - /tests/specs/app.forms.spec.js
[0-0]  Error:  Failed to create session.
read ECONNRESET
[0-0] FAILED in iOS - /tests/specs/app.forms.spec.js
[0-1] RUNNING in iOS - /tests/specs/app.login.spec.js
[0-1]  Error:  Failed to create session.
read ECONNRESET
[0-1] FAILED in iOS - /tests/specs/app.login.spec.js
[0-2] RUNNING in iOS - /tests/specs/app.navigation.spec.js
[0-2]  Error:  Failed to create session.
read ECONNRESET
[0-2] FAILED in iOS - /tests/specs/app.navigation.spec.js
[0-3] RUNNING in iOS - /tests/specs/app.swipe.spec.js
[0-3]  Error:  Failed to create session.
read ECONNRESET
[0-3] FAILED in iOS - /tests/specs/app.swipe.spec.js
[0-4] RUNNING in iOS - /tests/specs/app.webview.spec.js
[0-4]  Error:  Failed to create session.
read ECONNRESET
[0-4] FAILED in iOS - /tests/specs/app.webview.spec.js
[0-5] RUNNING in iOS - /tests/specs/app.webview.xpath.spec.js
[0-5]  Error:  Failed to create session.
read ECONNRESET
[0-5] FAILED in iOS - /tests/specs/app.webview.xpath.spec.js

Spec Files:	 0 passed, 6 failed, 6 total (100% completed) in 00:00:17 

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-boilerplate@5.3.1 ios.app: `wdio ./config/wdio.ios.app.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-boilerplate@5.3.1 ios.app script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dancoman/.npm/_logs/2020-11-30T20_44_38_790Z-debug.log
```

**Comment by desardavaishali** [comment]
I had a similar issue with WebDriverIO6. I closed the already running appium session and issue was resolved.
