### ISSUE TITLE
Failed to create session. The URL '/session' did not map to a valid resource

### ISSUE THREAD

**Issue by abubakarafzal** [webdriverio/appium-boilerplate#85]
**i am not able to execute this boilerplate in the Ios simulator?*
I installed all the packages and executing the npm script ios.app but not able to connect to my simulator and not able to open webdrverio app on the simulator.

this is the wdio.ios.app.conf.js
 'appium:deviceName': 'iPhone 8',
        'appium:platformVersion': '14.2',
        'appium:udid':'57BCE496-5E04-4DB3-9E39-8F65F96709E0',
        'appium:orientation': 'PORTRAIT',
        // `automationName` will be mandatory, see
        // https://github.com/appium/appium/releases/tag/v1.13.0
        'appium:automationName': 'XCUITest',
        // The path to the app
        'appium:app': join(process.cwd(), './apps/iOS-Simulator-NativeDemoApp-0.2.1.app.zip'),
        // Read the reset strategies very well, they differ per platform, see
        // http://appium.io/docs/en/writing-running-appium/other/reset-strategies/
        'appium:noReset': true,
        'appium:newCommandTimeout': 240,
**If it's about a specific piece of code, try and include some of it to support your question.**
[...]

**Environment :**
 - Node.js version: [e.g. 12]
 - NPM version: [e.g. 5.8.0]
 - Platform: [e.g. IOS]
 - Platform version: [e.g. 14.0]
 - Emulator/Simulator/Real Device: [e.g. Simulator]

**Appium Server LOGS**
{"capabilities":{"alwaysMatch":{"platformName":"iOS","appium:deviceName":"iPhone 8","appium:platformVersion":"14.2","appium:udid":"57BCE496-5E04-4DB3-9E39-8F65F96709E0","appium:orientation":"PORTRAIT","appium:automationName":"XCUITest","appium:app":"/Users/square63/Downloads/appium-boilerplate-master/apps/iOS-Simulator-NativeDemoApp-0.2.1.app.zip","appium:noReset":true,"appium:newCommandTimeout":240},"firstMatch":[{}]},"desiredCapabilities":{"platformName":"iOS","appium:deviceName":"iPhone 8","appium:platformVersion":"14.2","appium:udid":"57BCE496-5E04-4DB3-9E39-8F65F96709E0","appium:orientation":"PORTRAIT","appium:automationName":"XCUITest","appium:app":"/Users/square63/Downloads/appium-boilerplate-master/apps/iOS-Simulator-NativeDemoApp-0.2.1.app.zip","appium:noReset":true,"appium:newCommandTimeout":240}}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- POST /session 404 1 ms - 50

**Comment by GeekRishabh** [comment]
@abubakarafzal @suzuki Were you able to figure it out? I am facing the same issue
