### ISSUE TITLE
How do we use this boilerplate to integrate it with any CI/CD pipeline?

### ISSUE THREAD

**Issue by GeekRishabh** [webdriverio/appium-boilerplate#86]
I do have a react native application and I want to create a build and run the test cases on the CI/CD pipeline. Is there any documents or way to achieve it. I was referring to [Microsoft appcenter](https://appcenter.ms/) CI/CD but they don't provide support for the Webdriver or JS Appium. You can refer to the thread [here](https://github.com/MicrosoftDocs/appcenter-docs/issues/58) Let me know if there is any way we can achieve it?

**Comment by wswebcreation** [comment]
Hi @GeekRishabh 

Thanks for filing an issue, but this one is not related to this boilerplate. I also don't have a solution for you
