### ISSUE TITLE
Could not start the session

### ISSUE THREAD

**Issue by huwangtao123** [webdriverio/appium-boilerplate#87]
**Environment (please complete the following information):**
 - Node.js version: v12.18.4
 - NPM version: 0.36.0
 - Platform: IOS
 - Platform version:13.6
 - Emulator/Simulator/Real Device: Emulator

**Describe the bug**
Not able to create the session to execute the ios

**To Reproduce**
1. Clone the project and download the ios emulator app under ./apps folder
2. Modify the wdio.ios.app.conf.js 
```
   config.capabilities = [
    {
        // The defaults you need to have in your config
        platformName: 'iOS',
        maxInstances: 1,
        // For W3C the appium capabilities need to have an extension prefix
        // This is `appium:` for all Appium Capabilities which can be found here
        // http://appium.io/docs/en/writing-running-appium/caps/
        'appium:deviceName': 'iPhone 11 Pro Max',
        'appium:platformVersion': '13.6',
        'appium:orientation': 'PORTRAIT',
        // `automationName` will be mandatory, see
        // https://github.com/appium/appium/releases/tag/v1.13.0
        'appium:automationName': 'XCUITest',
        // The path to the app
        'appium:app': join(
            process.cwd(),
            './apps/iOS-Simulator-NativeDemoApp-0.2.1.app.zip'
        ),
        // Read the reset strategies very well, they differ per platform, see
        // http://appium.io/docs/en/writing-running-appium/other/reset-strategies/
        'appium:noReset': true,
        'appium:newCommandTimeout': 240,
    },
];
```
3. npm install && npm run ios.app

**Expected behavior**
The Appium session will be created and test will be running

**Screenshots**

**Additional context**
Appium 1.17.1

**Comment by huwangtao123** [comment]
![Screen Shot 2021-01-12 at 7 33 52 PM](https://user-images.githubusercontent.com/3118467/104403395-4970d800-550d-11eb-95c6-62d16fb4bf2f.png)

**Comment by huwangtao123** [comment]
[2021-01-13T03_20_34_756Z-debug.log](https://github.com/webdriverio/appium-boilerplate/files/5806254/2021-01-13T03_20_34_756Z-debug.log)

**Comment by wswebcreation** [comment]
@huwangtao123 

This has to do with the fact that you are starting Appium Desktop to listen to the wrong path, by default Appium will listen to the remote path `wd/hub` but WebdriverUI is not posting to that path. The challenge with Appium Desktop is that you can't tell it to start (from the initial screen) from a different remove path. 
So what you need to do is the following, go to you main config and add a path like this `path: 'wd/hub/'` 
See also the release notes of WebdriverIO V6 [here](https://webdriver.io/blog/2020/03/26/webdriverio-v6-released.html#other-changes)
That should work.

Closing it for now because it's not an issue with the boilerplate

**Comment by huwangtao123** [comment]
@wswebcreation 
Thanks for the quick response. I was able to use follow the release notes to start my appium with the cli argument --base-path / and start the test correctly.

However, when i try to add path: '/wd/hub' in my main config. it is not working for me.
I did try add the path in wdio.shared.conf.js file
1. inside of appium args
2. inside appium 
3. next to port

All 3 ways are not working. Do you know how do i add this path variable inside of my config file

**Comment by wswebcreation** [comment]
@huwangtao123 

Here's an example https://webdriver.io/docs/configurationfile.html

**Comment by huwangtao123** [comment]
@wswebcreation 
Thanks for the information.
However, after i set the path and hostname, i still see the same issue. (npm run ios.app). attach my wdio.shared.conf.js. Not sure how to debug on that the test start to post to new path.

`exports.config = {
    // ====================
    // Runner and framework
    // Configuration
    // ====================
    runner: 'local',
    hostname: 'localhost',
    port: 4723,
    path: '/wd/hub',
    framework: 'jasmine',
    jasmineNodeOpts: {
        // Updated the timeout to 30 seconds due to possible longer appium calls
        // When using XPATH
        defaultTimeoutInterval: 90000,
        helpers: [require.resolve('@babel/register')],
    },
    sync: true,
    logLevel: 'silent',
    deprecationWarnings: true,
    bail: 0,
    baseUrl: 'http://the-internet.herokuapp.com',
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    reporters: ['spec'],

    // ====================
    // Appium Configuration
    // ====================
    services: [
        [
            'appium',
            {
            // For options see
            // https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-appium-service
                args: {
                    // Auto download ChromeDriver
                    relaxedSecurity: true,
                    path: '/wd/hub'
                    // chromedriverAutodownload: true,
                    // For more arguments see
                    // https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-appium-service
                },
                command: 'appium',
            },
        ],
    ]
};
`

**Comment by wswebcreation** [comment]
@huwangtao123 

If you're using Appium Desktop and started the Appium server there you shouldn't use the Appium service

**Comment by huwangtao123** [comment]
Got it. It works well. Thanks.

One more question regarding selection strategy [Name](http://appium.io/docs/en/commands/element/find-elements/) for Appium. I am not able to find a good way to select it using webdriverIO. 
I did go though the selector page https://webdriver.io/docs/selectors.html and can not find the result.

**Comment by wswebcreation** [comment]
Hi @huwangtao123 

Here's a link about the mobile selectors, https://webdriver.io/docs/selectors.html#mobile-selectors, it all depends on how you want and can select your elements.

Future questions about WebdriverIo can better be asked on the [Gitter](https://gitter.im/webdriverio/webdriverio) channel if you don't mind. GitHub is more for issues 😉
