### ISSUE TITLE
Boilerplate is for Webdriver V7?

### ISSUE THREAD

**Issue by vjmaiky** [webdriverio/appium-boilerplate#88]
**Describe your question with as much detail as possible**
Hello. I'm new to using WebDriverIO. For the moment i'm trying to configure the boilerplate for V7 version. On V6 (this one seems to work), but when i switch it to the new version it is stuck in create session (app starts, session is created but if froze into that state).

**Environment (please complete the following information):**
 - Node.js version: 14.10.0
 - NPM version: 6.14.11]
 - Platform: Android
 - Platform version: 11
 - Emulator/Simulator/Real Device: Real Device

**Additional context**

`[Appium] New AndroidUiautomator2Driver session created successfully, session 134c6814-b8c0-456d-a5e3-c2d7374906cf added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1614064639111 (09:17:19 GMT+0200 (Eastern European Standard Time))
[debug] [W3C (134c6814)] Cached the protocol value 'W3C' for the new session 134c6814-b8c0-456d-a5e3-c2d7374906cf
[debug] [W3C (134c6814)] Responding to client with driver.createSession() result: {"capabilities":{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"Android","deviceName":"HT8281A03687","platformVersion":"11","orientation":"PORTRAIT","automationName":"UiAutomator2","app":"/Users/Shared/Framework/automationUniversity/apps/myapp.apk","noReset":true,"newCommandTimeout":240},"platformName":"Android","deviceName":"HT8281A03687","platformVersion":"11","orientation":"PORTRAIT","automationName":"UiAutomator2","app":"/Users/Shared/Framework/automationUniversity/apps/myapp.apk","noReset":true,"newCommandTimeout":240,"deviceUDID":"HT8281A03687","appPackage":"com.myapp.flynet","deviceApiLevel":30,"deviceScreenSize":"1080x1920","deviceScreenDensity":420,"deviceModel":"Pixel 2","deviceManufacturer":"Google","pixelRatio":2.625,"statBarHeight":63,"viewportRect":{"left":0,"top":63,"width":1080,"heigh...
[HTTP] <-- POST /wd/hub/session 200 7902 ms - 1092
[HTTP] `

Do i need to do something extra?
I will put here my dependencies:
`  "devDependencies": {
    "@babel/register": "^7.12.13",
    "@wdio/allure-reporter": "^7.0.7",
    "@wdio/appium-service": "^7.0.7",
    "@wdio/cli": "^7.0.7",
    "@wdio/local-runner": "^7.0.7",
    "@wdio/mocha-framework": "^7.0.7",
    "@wdio/selenium-standalone-service": "^7.0.7",
    "@wdio/spec-reporter": "^7.0.7",
    "@wdio/sync": "^7.0.7",
    "appium": "^1.20.2",
    "chai": "^4.3.0"
  }`

**Comment by christian-bromann** [comment]
Which boilerplate are you trying to use? Currently only our [jasmine boilerplate](https://github.com/webdriverio/jasmine-boilerplate) was updated to v7. The others will come within the next weeks.

**Comment by vjmaiky** [comment]
> Which boilerplate are you trying to use? Currently only our [jasmine boilerplate](https://github.com/webdriverio/jasmine-boilerplate) was updated to v7. The others will come within the next weeks.

than i have my answer; i was trying to use this boiler (appium) with version 7.0.7 of webdriverIO; do you have an estimate when this will be updated to v7?

**Comment by christian-bromann** [comment]
> do you have an estimate when this will be updated to v7?

No, feel free to take a stab at it.

**Comment by wswebcreation** [comment]
@vjmaiky 

I'm working on it, see https://github.com/webdriverio/appium-boilerplate/pull/100. I'm also adding new features. I hope to have it done beginning of next week

**Comment by wswebcreation** [comment]
The boilerplate has been updated to V7, closing this one
